Repository FuelLabs/fuel-core, pull requests merged in 2022-04, with the labels that each got.

#256 Capitalize GQL field descriptions
  fuel-client/assets/schema.sdl
  fuel-core/src/schema/block.rs
  fuel-core/src/schema/coin.rs
  fuel-core/src/schema/tx.rs
Labels: documentation

#237 feat: add `excluded_ids` argument to `Query.coinsToSpend`
  fuel-client/assets/schema.sdl
  fuel-client/src/client.rs
  fuel-client/src/client/schema/coin.rs
  fuel-client/src/client/schema/primitives.rs
  fuel-core/src/coin_query.rs
  fuel-core/src/schema/coin.rs
  fuel-tests/tests/coin.rs
Labels: enhancement

#257 feat: add `Query.{balance,balances}` to GraphQL schema
  fuel-client/assets/schema.sdl
  fuel-client/src/client.rs
  fuel-client/src/client/schema.rs
  fuel-client/src/client/schema/balance.rs
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__balance__tests__balance_query_gql_output.snap
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__balance__tests__balances_connection_query_gql_output.snap
  fuel-core/src/schema.rs
  fuel-core/src/schema/balance.rs
  fuel-tests/tests/balances.rs
  fuel-tests/tests/lib.rs
Labels: enhancement

#285 bump to support jnzi
  Cargo.lock
  fuel-client/Cargo.toml
  fuel-core-interfaces/Cargo.toml
  fuel-core/Cargo.toml
  fuel-tests/Cargo.toml
  fuel-txpool/Cargo.toml
Labels: breaking

#299 Cleanup all removed dependencies
  fuel-txpool/src/txpool.rs
Labels: bug
