Repository FuelLabs/fuel-core, pull requests merged in 2022-02, with the labels that each got.

#157 add new tx fields (byte_price + storage_slots)
  Cargo.lock
  fuel-client/Cargo.toml
  fuel-client/assets/schema.sdl
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__tx__tests__transparent_transaction_by_id_query_gql_output.snap
  fuel-client/src/client/schema/tx/tests/transparent_tx.rs
  fuel-client/tests/tx.rs
  fuel-core-interfaces/Cargo.toml
  fuel-core-interfaces/src/db.rs
  fuel-core/Cargo.toml
  fuel-core/src/schema/tx/types.rs
  fuel-core/src/service.rs
  fuel-core/src/state.rs
  fuel-txpool/Cargo.toml
  fuel-txpool/src/containers/dependency.rs
Labels: enhancement, breaking

#159 Master Branch Fix - Update Rust toolchain in docker
  README.md
  deployment/Dockerfile
Labels: bug

#169 add basic contributing file
  CONTRIBUTING.md
  README.md
Labels: documentation

#131 Add `Query.coinsToSpend` to GQL schema
  Cargo.lock
  fuel-client/Cargo.toml
  fuel-client/assets/schema.sdl
  fuel-client/src/client.rs
  fuel-client/src/client/schema/coin.rs
  fuel-client/tests/coin.rs
  fuel-core/Cargo.toml
  fuel-core/src/coin_query.rs
  fuel-core/src/database/coin.rs
  fuel-core/src/lib.rs
  fuel-core/src/main.rs
  fuel-core/src/schema/coin.rs
Labels: enhancement

#151 p2p discovery
  Cargo.lock
  Cargo.toml
  fuel-p2p/Cargo.toml
  fuel-p2p/src/behavior.rs
  fuel-p2p/src/config.rs
  fuel-p2p/src/discovery.rs
  fuel-p2p/src/discovery/discovery_config.rs
  fuel-p2p/src/discovery/mdns.rs
  fuel-p2p/src/lib.rs
  fuel-p2p/src/service.rs
Labels: enhancement

#177 Receipt saving bug
  fuel-core/src/executor.rs
Labels: bug
