Repository FuelLabs/fuel-core, pull requests merged in 2022-12, with the labels that each got.

#811 Use `tokio::main` for `fuel-gql-client` cli
  Cargo.lock
  fuel-client/Cargo.toml
  fuel-client/src/main.rs
Labels: bug, enhancement

#814 Move block producer requirements into corresponding crates
  Cargo.lock
  fuel-block-producer/Cargo.toml
  fuel-block-producer/src/block_producer.rs
  fuel-block-producer/src/block_producer/tests.rs
  fuel-block-producer/src/mocks.rs
  fuel-block-producer/src/ports.rs
  fuel-block-producer/tests/integration.rs
  fuel-core-bft/src/service.rs
  fuel-core-interfaces/src/block_producer.rs
  fuel-core-interfaces/src/lib.rs
  fuel-core/src/schema/tx.rs
  fuel-core/src/service.rs
  fuel-core/src/service/adapters.rs
  fuel-core/src/service/modules.rs
  fuel-poa-coordinator/Cargo.toml
  fuel-poa-coordinator/src/lib.rs
  fuel-poa-coordinator/src/ports.rs
  fuel-poa-coordinator/src/service.rs
  fuel-poa-coordinator/tests/test_trigger.rs
  version-compatibility/Cargo.lock
Labels: breaking, fuel-block-executor, architecture

#779 add reserved nodes
  fuel-core/src/cli/run/p2p.rs
  fuel-p2p/src/behavior.rs
  fuel-p2p/src/config.rs
  fuel-p2p/src/discovery.rs
  fuel-p2p/src/discovery/discovery_config.rs
  fuel-p2p/src/gossipsub/config.rs
  fuel-p2p/src/service.rs
  fuel-tests/tests/tx_gossip.rs
Labels: fuel-p2p, architecture

#819 Bugfix: Race conditions between read and write into database
  Cargo.lock
  fuel-block-producer/src/block_producer.rs
  fuel-block-producer/src/block_producer/tests.rs
  fuel-block-producer/src/db.rs
  fuel-block-producer/src/lib.rs
  fuel-block-producer/src/mocks.rs
  fuel-block-producer/src/ports.rs
  fuel-block-producer/tests/integration.rs
  fuel-core-interfaces/src/db.rs
  fuel-core-interfaces/src/executor.rs
  fuel-core-interfaces/src/poa_coordinator.rs
  fuel-core/src/database.rs
  fuel-core/src/database/transactional.rs
  fuel-core/src/executor.rs
  fuel-core/src/schema/block.rs
  fuel-core/src/schema/tx.rs
  fuel-core/src/service/adapters.rs
  fuel-core/src/service/genesis.rs
  fuel-core/src/service/modules.rs
  fuel-poa-coordinator/src/ports.rs
  fuel-poa-coordinator/src/service.rs
  fuel-poa-coordinator/tests/test_trigger.rs
  fuel-tests/Cargo.toml
  fuel-tests/tests/tx.rs
Labels: bug

#785 add chain id & chain config check to peering process
  fuel-core/src/cli/run.rs
  fuel-core/src/cli/run/p2p.rs
  fuel-p2p/src/config.rs
  fuel-p2p/src/service.rs
Labels: fuel-p2p

#822 Close Tx Status SSE stream before EOF is encountered
  fuel-client/src/client.rs
Labels: bug

#825 Bugfix: Support script txs with empty script
  Cargo.lock
Labels: bug

#827 unify chain id generation and usage
  Cargo.lock
  fuel-block-executor/Cargo.toml
  fuel-block-executor/src/refs.rs
  fuel-block-executor/src/refs/contract.rs
  fuel-chain-config/Cargo.toml
  fuel-chain-config/src/config/chain.rs
  fuel-chain-config/src/config/coin.rs
  fuel-chain-config/src/config/message.rs
  fuel-chain-config/src/genesis.rs
  fuel-chain-config/src/lib.rs
  fuel-core-interfaces/src/model/block.rs
  fuel-core/src/cli/run.rs
  fuel-core/src/cli/run/p2p.rs
  fuel-core/src/database.rs
  fuel-core/src/database/block.rs
  fuel-core/src/database/sealed_block.rs
  fuel-core/src/service/config.rs
  fuel-core/src/service/genesis.rs
  fuel-core/src/service/modules.rs
  fuel-p2p/Cargo.toml
  fuel-p2p/src/behavior.rs
  fuel-p2p/src/config.rs
  fuel-p2p/src/gossipsub/config.rs
  fuel-p2p/src/orchestrator.rs
  fuel-p2p/src/service.rs
  version-compatibility/Cargo.lock
Labels: chainspec

#755 More integration tests for PoA block triggering behavior
  .gitignore
  fuel-tests/Cargo.toml
  fuel-tests/tests/lib.rs
  fuel-tests/tests/trigger_integration/hybrid.rs
  fuel-tests/tests/trigger_integration/instant.rs
  fuel-tests/tests/trigger_integration/interval.rs
  fuel-tests/tests/trigger_integration/mod.rs
  fuel-tests/tests/trigger_integration/never.rs
  version-compatibility/Cargo.lock
Labels: tech-debt

#775 Return error for no argument pagination
  fuel-client/assets/schema.sdl
  fuel-client/src/client/schema.rs
  fuel-core/src/database/transaction.rs
  fuel-core/src/schema.rs
  fuel-core/src/schema/balance.rs
  fuel-core/src/schema/block.rs
  fuel-core/src/schema/coin.rs
  fuel-core/src/schema/contract.rs
  fuel-core/src/schema/message.rs
  fuel-core/src/schema/scalars.rs
  fuel-core/src/schema/scalars/utxo_id.rs
  fuel-core/src/schema/tx.rs
  fuel-core/src/schema/tx/types.rs
  fuel-tests/tests/blocks.rs
  fuel-tests/tests/coin.rs
  fuel-tests/tests/contract.rs
  fuel-tests/tests/tx.rs
Labels: graphql-api

#834 Return error for no argument pagination (#775)
  fuel-client/assets/schema.sdl
  fuel-client/src/client/schema.rs
  fuel-core/src/database/transaction.rs
  fuel-core/src/schema.rs
  fuel-core/src/schema/balance.rs
  fuel-core/src/schema/block.rs
  fuel-core/src/schema/coin.rs
  fuel-core/src/schema/contract.rs
  fuel-core/src/schema/message.rs
  fuel-core/src/schema/scalars.rs
  fuel-core/src/schema/scalars/utxo_id.rs
  fuel-core/src/schema/tx.rs
  fuel-core/src/schema/tx/types.rs
  fuel-tests/tests/blocks.rs
  fuel-tests/tests/coin.rs
  fuel-tests/tests/contract.rs
  fuel-tests/tests/tx.rs
Labels: breaking

#836 Attached coinbase transaction to the owners table
  fuel-core/src/executor.rs
  fuel-tests/tests/tx.rs
Labels: bug

#864 Fix Windows Compilation
  crates/fuel-core/src/service.rs
Labels: bug

#869 Fix Request Body Size Limit
  crates/fuel-core/src/service/graph_api.rs
  deployment/ingress/eks/fuel-core-ingress.yaml
  deployment/scripts/chainspec/dev_chainspec.json
Labels: bug
