Repository FuelLabs/fuel-core, pull requests merged in 2022-07, with the labels that each got.

#453 chore: use `concurrency` to cancel previous CI runs
  .github/workflows/ci.yml
Labels: tech-debt

#269 chore: improve balance test
  fuel-tests/tests/balances.rs
Labels: tech-debt

#459 Feat: Use in-memory binary Merkle tree
  Cargo.lock
  fuel-core-interfaces/Cargo.toml
  fuel-core/src/executor.rs
Labels: enhancement, fuel-core-interfaces

#450 Relayer integration. ServiceBuilder. Context
  fuel-block-importer/src/service.rs
  fuel-block-producer/src/service.rs
  fuel-client/src/client.rs
  fuel-core-bft/src/service.rs
  fuel-core-interfaces/src/block_importer.rs
  fuel-core-interfaces/src/relayer.rs
  fuel-core-interfaces/src/txpool.rs
  fuel-core/src/args.rs
  fuel-core/src/config.rs
  fuel-core/src/database.rs
  fuel-core/src/database/metadata.rs
  fuel-core/src/service.rs
  fuel-core/src/service/genesis.rs
  fuel-core/src/service/modules.rs
  fuel-core/src/state/rocks_db.rs
  fuel-relayer/Cargo.toml
  fuel-relayer/README.md
  fuel-relayer/src/bin/testrun.rs
  fuel-relayer/src/config.rs
  fuel-relayer/src/lib.rs
  fuel-relayer/src/relayer.rs
  fuel-relayer/src/service.rs
  fuel-relayer/src/test_helpers/mod.rs
  fuel-sync/src/service.rs
  fuel-txpool/src/service.rs
Labels: enhancement, fuel-relayer

#441 implement DummyDB functionality for tests
  fuel-core-interfaces/src/db.rs
Labels: enhancement, fuel-database

#435 Snapshot to chainspec command
  Cargo.lock
  deployment/Dockerfile
  fuel-core/Cargo.toml
  fuel-core/src/args.rs
  fuel-core/src/args/run.rs
  fuel-core/src/args/snapshot.rs
  fuel-core/src/config/chain_config.rs
  fuel-core/src/database/coin.rs
  fuel-core/src/database/contracts.rs
  fuel-core/src/main.rs
  fuel-tests/Cargo.toml
  fuel-tests/tests/helpers.rs
  fuel-tests/tests/lib.rs
  fuel-tests/tests/snapshot.rs
Labels: enhancement

#468 Legacy cli
  fuel-core/src/args/snapshot.rs
  fuel-core/src/cli.rs
  fuel-core/src/cli/run.rs
  fuel-core/src/cli/snapshot.rs
  fuel-core/src/main.rs
Labels: fuel-core

#467 Fix Dockerfile to support `fuel-core run`
  deployment/Dockerfile
  deployment/charts/templates/fuel-core-deploy.yaml
Labels: bug

#402 Network Orchestrator service proposal
  fuel-core-interfaces/src/model.rs
  fuel-core-interfaces/src/model/vote.rs
  fuel-core-interfaces/src/p2p.rs
  fuel-p2p/src/behavior.rs
  fuel-p2p/src/codecs.rs
  fuel-p2p/src/codecs/bincode.rs
  fuel-p2p/src/gossipsub.rs
  fuel-p2p/src/gossipsub/messages.rs
  fuel-p2p/src/gossipsub/topics.rs
  fuel-p2p/src/lib.rs
  fuel-p2p/src/orchestrator.rs
  fuel-p2p/src/request_response/messages.rs
  fuel-p2p/src/service.rs
Labels: enhancement

#456 TxPool ServiceBuilder and Context
  fuel-core/src/service/modules.rs
  fuel-txpool/src/interface.rs
  fuel-txpool/src/lib.rs
  fuel-txpool/src/service.rs
  fuel-txpool/src/txpool.rs
Labels: fuel-txpool, fuel-core

#461 Controlc/block api
  fuel-client/assets/schema.sdl
  fuel-client/src/client.rs
  fuel-client/src/client/schema/block.rs
  fuel-core/src/cli/run.rs
  fuel-core/src/config.rs
  fuel-core/src/schema.rs
  fuel-core/src/schema/block.rs
  fuel-tests/tests/blocks.rs
Labels: enhancement

#475 remove tempdir
  Cargo.lock
  fuel-tests/Cargo.toml
Labels: enhancement

#495 Cli print formatted error on exit
  Cargo.lock
  fuel-core/Cargo.toml
  fuel-core/src/cli.rs
Labels: bug, fuel-core

#493 style: %s/produce_block/produce_blocks/g
  fuel-client/assets/schema.sdl
  fuel-client/src/client.rs
  fuel-client/src/client/schema/block.rs
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__block__tests__block_mutation_query_gql_output.snap
  fuel-core/src/schema/block.rs
  fuel-tests/tests/blocks.rs
Labels: tech-debt

#502 Fix a bunch of typos and general cleanup.
  CONTRIBUTING.md
  README.md
  deployment/README.md
  fuel-block-executor/README.md
  fuel-block-importer/README.md
  fuel-block-producer/README.md
  fuel-client/src/client/schema/coin.rs
  fuel-core-bft/README.md
  fuel-core-interfaces/README.md
  fuel-core-interfaces/src/db.rs
  fuel-core-interfaces/src/model/block.rs
  fuel-core-interfaces/src/model/deposit_coin.rs
  fuel-core-interfaces/src/model/txpool.rs
  fuel-core-interfaces/src/relayer.rs
  fuel-core-interfaces/src/sync.rs
  fuel-core-interfaces/src/txpool.rs
  fuel-core/src/cli/run/relayer.rs
  fuel-core/src/coin_query.rs
  fuel-core/src/database.rs
  fuel-core/src/database/metadata.rs
  fuel-core/src/executor.rs
  fuel-core/src/schema/tx.rs
  fuel-core/src/schema/tx/types.rs
  fuel-core/src/service.rs
  fuel-core/src/state/in_memory/transaction.rs
  fuel-p2p/Cargo.toml
  fuel-p2p/src/behavior.rs
  fuel-p2p/src/gossipsub/topics.rs
  fuel-p2p/src/service.rs
  fuel-relayer/README.md
  fuel-relayer/abi/ValidatorSet.json
  fuel-relayer/src/config.rs
  fuel-relayer/src/finalization_queue.rs
  fuel-relayer/src/log.rs
  fuel-relayer/src/pending_blocks.rs
  fuel-relayer/src/relayer.rs
  fuel-relayer/src/service.rs
  fuel-relayer/src/validators.rs
  fuel-sync/README.md
  fuel-tests/tests/tx.rs
  fuel-txpool/README.md
  fuel-txpool/src/containers/dependency.rs
  fuel-txpool/src/service.rs
  fuel-txpool/src/txpool.rs
Labels: tech-debt

#485 Relayer DaMessage
  fuel-core-interfaces/src/db.rs
  fuel-core-interfaces/src/model.rs
  fuel-core-interfaces/src/model/block.rs
  fuel-core-interfaces/src/model/deposit_coin.rs
  fuel-core-interfaces/src/model/messages.rs
  fuel-core-interfaces/src/relayer.rs
  fuel-core/src/cli/run/relayer.rs
  fuel-core/src/database.rs
  fuel-core/src/database/deposit_coin.rs
  fuel-core/src/database/message.rs
  fuel-relayer/README.md
  fuel-relayer/abi/IFuelMessageOutbox.json
  fuel-relayer/src/abi.rs
  fuel-relayer/src/config.rs
  fuel-relayer/src/finalization_queue.rs
  fuel-relayer/src/log.rs
  fuel-relayer/src/relayer.rs
  fuel-relayer/src/service.rs
Labels: fuel-relayer

#508 feat: improve correctness of pagination
  fuel-core/src/schema/balance.rs
  fuel-core/src/schema/block.rs
  fuel-core/src/schema/coin.rs
  fuel-core/src/schema/tx.rs
Labels: tech-debt
