Repository FuelLabs/fuel-core, pull requests merged in 2022-08, with the labels that each got.

#531 Document workaround for low file descriptor limits
  README.md
Labels: bug, documentation

#535 Update ethers version to `0.17`
  Cargo.lock
  fuel-relayer/Cargo.toml
Labels: bug

#532 Message verification in the block executor
  fuel-core/src/executor.rs
Labels: enhancement, breaking, fuel-block-executor

#548 v0.10.0
  Cargo.lock
  deployment/charts/Chart.yaml
  fuel-block-executor/Cargo.toml
  fuel-block-importer/Cargo.toml
  fuel-block-producer/Cargo.toml
  fuel-client/Cargo.toml
  fuel-core-bft/Cargo.toml
  fuel-core-interfaces/Cargo.toml
  fuel-core/Cargo.toml
  fuel-p2p/Cargo.toml
  fuel-relayer/Cargo.toml
  fuel-sync/Cargo.toml
  fuel-txpool/Cargo.toml
Labels: breaking

#572 Rename Deposit event from Ethereum as StakingDeposit
  fuel-relayer/src/finalization_queue.rs
  fuel-relayer/src/log.rs
Labels: tech-debt

#492 Include p2p into fuel core
  Cargo.lock
  fuel-core-bft/src/service.rs
  fuel-core-interfaces/src/p2p.rs
  fuel-core/Cargo.toml
  fuel-core/src/cli.rs
  fuel-core/src/cli/run.rs
  fuel-core/src/cli/run/p2p.rs
  fuel-core/src/database.rs
  fuel-core/src/service/config.rs
  fuel-core/src/service/modules.rs
  fuel-p2p/Cargo.toml
  fuel-p2p/src/behavior.rs
  fuel-p2p/src/config.rs
  fuel-p2p/src/discovery.rs
  fuel-p2p/src/discovery/discovery_config.rs
  fuel-p2p/src/lib.rs
  fuel-p2p/src/orchestrator.rs
  fuel-p2p/src/service.rs
  fuel-sync/src/service.rs
Labels: fuel-core, fuel-p2p

#573 Add a .dockerignore file
  deployment/.dockerignore
Labels: tech-debt

#581 Transaction selection logic for the block producer
  Cargo.lock
  fuel-block-producer/Cargo.toml
  fuel-block-producer/src/block_producer/tests.rs
  fuel-block-producer/src/block_producer/transaction_selector.rs
  fuel-block-producer/src/config.rs
Labels: fuel-block-producer

#587 Improve txpool docs
  fuel-core-interfaces/src/txpool.rs
  fuel-txpool/README.md
Labels: documentation, fuel-txpool, tech-debt
