Repository FuelLabs/fuel-core, pull requests merged in 2022-11, with the labels that each got.

#758 Change timestamps from chrono to tai64
  Cargo.lock
  fuel-block-producer/Cargo.toml
  fuel-block-producer/src/block_producer.rs
  fuel-client/Cargo.toml
  fuel-client/assets/schema.sdl
  fuel-client/src/client/schema/block.rs
  fuel-client/src/client/schema/primitives.rs
  fuel-client/src/client/schema/tx.rs
  fuel-client/src/client/types.rs
  fuel-core-interfaces/Cargo.toml
  fuel-core-interfaces/src/lib.rs
  fuel-core-interfaces/src/model/block.rs
  fuel-core-interfaces/src/model/txpool.rs
  fuel-core/Cargo.toml
  fuel-core/src/database/block.rs
  fuel-core/src/database/vm_database.rs
  fuel-core/src/executor.rs
  fuel-core/src/query/message_proof/test.rs
  fuel-core/src/schema/block.rs
  fuel-core/src/schema/scalars.rs
  fuel-core/src/schema/tx/types.rs
  fuel-core/src/tx_pool.rs
  fuel-relayer/Cargo.toml
  fuel-tests/Cargo.toml
  fuel-tests/tests/blocks.rs
  fuel-tests/tests/messages.rs
  fuel-tests/tests/tx.rs
  fuel-txpool/Cargo.toml
Labels: breaking

#745 expose get_peers_ids() from Network Service
  fuel-core/src/service/modules.rs
  fuel-p2p/src/orchestrator.rs
  fuel-p2p/src/service.rs
Labels: enhancement

#717 Introduce txpool and p2p metrics
  Cargo.lock
  fuel-block-executor/src/config.rs
  fuel-core/Cargo.toml
  fuel-core/src/cli/run.rs
  fuel-core/src/service/metrics.rs
  fuel-core/src/service/modules.rs
  fuel-core/src/state/rocks_db.rs
  fuel-metrics/Cargo.toml
  fuel-metrics/src/core_metrics.rs
  fuel-metrics/src/lib.rs
  fuel-metrics/src/p2p_metrics.rs
  fuel-metrics/src/service.rs
  fuel-metrics/src/txpool_metrics.rs
  fuel-p2p/Cargo.toml
  fuel-p2p/src/gossipsub/config.rs
  fuel-p2p/src/service.rs
  fuel-tests/Cargo.toml
  fuel-tests/tests/lib.rs
  fuel-tests/tests/metrics.rs
  fuel-txpool/Cargo.toml
  fuel-txpool/src/config.rs
  fuel-txpool/src/txpool.rs
Labels: enhancement

#767 fix bug where txs wouldn't get squeezed if coin state already existed
  fuel-txpool/src/containers/dependency.rs
  fuel-txpool/src/txpool/tests.rs
Labels: bug

#770 Expose signature of the block, if any in GraphQL
  Cargo.lock
  Cargo.toml
  fuel-client/assets/schema.sdl
  fuel-client/src/client/schema/block.rs
  fuel-client/src/client/schema/primitives.rs
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__block__tests__block_by_id_query_gql_output.snap
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__block__tests__blocks_connection_query_gql_output.snap
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__chain__tests__chain_gql_query_output.snap
  fuel-core/src/schema/block.rs
  fuel-tests/tests/blocks.rs
  fuel-tests/tests/chain.rs
  version-compatibility/0.14.1-0.15.0/Cargo.toml
  version-compatibility/0.14.1-0.15.0/dummy.rs
  version-compatibility/0.14.1-0.15.0/fuel-core:0.14.1-client:0.15.0/Cargo.toml
  version-compatibility/0.14.1-0.15.0/fuel-core:0.14.1-client:0.15.0/test.rs
  version-compatibility/0.14.1-0.15.0/fuel-core:0.15.0-client:0.14.1/Cargo.toml
  version-compatibility/0.14.1-0.15.0/fuel-core:0.15.0-client:0.14.1/test.rs
  version-compatibility/Cargo.toml
  version-compatibility/dummy.rs
Labels: breaking

#783 add public address for local node to be reachable for the nodes in the network
  fuel-core/src/cli/run/p2p.rs
  fuel-p2p/src/config.rs
  fuel-p2p/src/service.rs
Labels: fuel-p2p

#786 Use `http-reqwest` instead of `http-surf`
  Cargo.lock
  fuel-client/Cargo.toml
  fuel-client/src/client.rs
  version-compatibility/0.14.1-0.15.0/fuel-core:0.14.1-client:0.15.0/test.rs
  version-compatibility/0.14.1-0.15.0/fuel-core:0.15.0-client:0.14.1/test.rs
Labels: breaking, graphql-api

#800 Use ascending order for blocks
  fuel-core/src/schema/block.rs
  fuel-tests/tests/blocks.rs
Labels: bug
