Repository FuelLabs/fuel-core, pull requests merged in 2022-05, with the labels that each got.

#307 Add ability to set minimum required gas / byte fees on transactions
  deployment/charts/templates/fuel-core-deploy.yaml
  deployment/charts/values.yaml
  deployment/scripts/.env
  fuel-core-interfaces/src/db.rs
  fuel-core-interfaces/src/txpool.rs
  fuel-core/src/args.rs
  fuel-core/src/main.rs
  fuel-core/src/service.rs
  fuel-core/src/tx_pool.rs
  fuel-txpool/src/config.rs
  fuel-txpool/src/service.rs
  fuel-txpool/src/txpool.rs
Labels: enhancement

#207 Relayer skeleton impl
  Cargo.lock
  Cargo.toml
  docs/diagrams/fuel_v2_relayer_sliding_window.jpg
  fuel-core-interfaces/src/block_importer.rs
  fuel-core-interfaces/src/db.rs
  fuel-core-interfaces/src/lib.rs
  fuel-core-interfaces/src/model.rs
  fuel-core-interfaces/src/model/validator_stake.rs
  fuel-core-interfaces/src/relayer.rs
  fuel-core-interfaces/src/signer.rs
  fuel-core/Cargo.toml
  fuel-core/src/database.rs
  fuel-core/src/database/deposit_coin.rs
  fuel-core/src/database/metadata.rs
  fuel-core/src/database/validator_set.rs
  fuel-core/src/database/validator_set_diffs.rs
  fuel-core/src/state/in_memory/memory_store.rs
  fuel-core/src/state/in_memory/transaction.rs
  fuel-p2p/src/discovery/discovery_config.rs
  fuel-p2p/src/discovery/mdns.rs
  fuel-relayer/Cargo.toml
  fuel-relayer/README.md
  fuel-relayer/src/bin/testrun.rs
  fuel-relayer/src/config.rs
  fuel-relayer/src/lib.rs
  fuel-relayer/src/log.rs
  fuel-relayer/src/pending_events.rs
  fuel-relayer/src/relayer.rs
  fuel-relayer/src/service.rs
  fuel-relayer/src/test_helpers/middleware.rs
  fuel-relayer/src/test_helpers/mod.rs
  fuel-relayer/src/validator_set.rs
  fuel-txpool/src/containers/price_sort.rs
  fuel-txpool/src/service.rs
  fuel-txpool/src/subscribers.rs
  fuel-txpool/src/txpool.rs
Labels: enhancement

#312 TxPool config fix
  Cargo.lock
  fuel-core/src/executor.rs
  fuel-core/src/tx_pool.rs
  fuel-tests/Cargo.toml
  fuel-tests/tests/tx.rs
  fuel-tests/tests/tx/utxo_validation.rs
Labels: bug

#323 fix: has next page
  fuel-client/src/client/schema.rs
  fuel-client/src/client/schema/balance.rs
  fuel-client/src/client/schema/block.rs
  fuel-client/src/client/schema/coin.rs
  fuel-client/src/client/schema/tx.rs
  fuel-core/src/schema/tx.rs
  fuel-tests/tests/tx.rs
Labels: bug

#328 Update fuel core to latest deps (fuel-tx 0.10, fuel-vm 0.9, fuel-crypto 0.5)
  Cargo.lock
  fuel-client/Cargo.toml
  fuel-client/assets/schema.sdl
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__tx__tests__transparent_transaction_by_id_query_gql_output.snap
  fuel-client/src/client/schema/tx/tests/transparent_tx.rs
  fuel-core-interfaces/Cargo.toml
  fuel-core-interfaces/src/model/block.rs
  fuel-core-interfaces/src/model/block_height.rs
  fuel-core-interfaces/src/model/coin.rs
  fuel-core-interfaces/src/relayer.rs
  fuel-core-interfaces/src/txpool.rs
  fuel-core/Cargo.toml
  fuel-core/src/schema/tx/types.rs
  fuel-relayer/Cargo.toml
  fuel-tests/Cargo.toml
  fuel-txpool/Cargo.toml
  fuel-txpool/src/txpool.rs
Labels: breaking

#354 readme update
  README.md
Labels: documentation

#350 Update Contracts API Endpoints
  fuel-client/assets/schema.sdl
  fuel-client/src/client.rs
  fuel-client/src/client/schema/contract.rs
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__contract__tests__contract_by_id_query_gql_output.snap
  fuel-core/src/schema.rs
  fuel-core/src/schema/contract.rs
  fuel-tests/tests/contract.rs
  fuel-tests/tests/helpers.rs
  fuel-tests/tests/lib.rs
  fuel-tests/tests/tx.rs
  fuel-tests/tests/tx/utxo_validation.rs
Labels: enhancement
