Repository FuelLabs/fuel-core, pull requests merged in 2022-06, with the labels that each got.

#376 Add Contract Balances API
  Cargo.lock
  fuel-client/assets/schema.sdl
  fuel-client/src/client.rs
  fuel-client/src/client/schema/contract.rs
  fuel-core/src/database/coin.rs
  fuel-core/src/database/contracts.rs
  fuel-core/src/schema/contract.rs
  fuel-tests/Cargo.toml
  fuel-tests/tests/contract.rs
Labels: enhancement

#394 p2p messages with dummy consensus Vote
  Cargo.lock
  fuel-core-interfaces/Cargo.toml
  fuel-core-interfaces/src/model.rs
  fuel-core-interfaces/src/model/vote.rs
  fuel-p2p/Cargo.toml
  fuel-p2p/src/behavior.rs
  fuel-p2p/src/codecs/bincode.rs
  fuel-p2p/src/config.rs
  fuel-p2p/src/gossipsub/messages.rs
  fuel-p2p/src/request_response/messages.rs
  fuel-p2p/src/service.rs
Labels: enhancement

#404 Database/RocksDb Metrics
  Cargo.lock
  fuel-core/Cargo.toml
  fuel-core/src/args.rs
  fuel-core/src/service.rs
  fuel-core/src/service/graph_api.rs
  fuel-core/src/service/metrics.rs
  fuel-core/src/state/rocks_db.rs
  fuel-tests/Cargo.toml
  fuel-tests/tests/lib.rs
  fuel-tests/tests/metrics.rs
Labels: enhancement

#377 Validators get
  fuel-core-interfaces/src/relayer.rs
  fuel-relayer/src/finalization_queue.rs
  fuel-relayer/src/relayer.rs
  fuel-relayer/src/validators.rs
Labels: enhancement, fuel-relayer

#422 fix: use gas_price_factor to verify FeeAmount
  fuel-core/src/executor.rs
Labels: bug

#427 Add Metrics to Batch Write and Key Length Fix
  fuel-core/src/state/rocks_db.rs
  fuel-tests/tests/metrics.rs
Labels: bug

#421 ValidatorAddress and ConsensusPublicKey types
  fuel-core-interfaces/src/db.rs
  fuel-core-interfaces/src/model.rs
  fuel-core-interfaces/src/relayer.rs
  fuel-core/src/database.rs
  fuel-core/src/database/validator_set.rs
  fuel-relayer/src/finalization_queue.rs
  fuel-relayer/src/log.rs
  fuel-relayer/src/validators.rs
Labels: enhancement

#407 txpool channels
  fuel-block-producer/src/service.rs
  fuel-core-interfaces/src/txpool.rs
  fuel-core/src/database.rs
  fuel-core/src/executor.rs
  fuel-core/src/schema/tx.rs
  fuel-core/src/schema/tx/types.rs
  fuel-core/src/service/graph_api.rs
  fuel-core/src/service/modules.rs
  fuel-core/src/tx_pool.rs
  fuel-txpool/src/interface.rs
  fuel-txpool/src/lib.rs
  fuel-txpool/src/service.rs
  fuel-txpool/src/subscribers.rs
Labels: enhancement

#439 run rust-comby
  fuel-p2p/src/codecs/bincode.rs
  fuel-relayer/src/relayer.rs
Labels: enhancement

#438 Wrap txpool sender
  fuel-block-producer/src/service.rs
  fuel-core-interfaces/src/txpool.rs
  fuel-core/src/schema/tx.rs
  fuel-txpool/src/service.rs
Labels: enhancement, fuel-txpool

#440 Move config to separate mod. Include module configurations.
  Cargo.lock
  fuel-block-executor/src/config.rs
  fuel-block-executor/src/lib.rs
  fuel-block-importer/src/config.rs
  fuel-block-producer/src/config.rs
  fuel-core-bft/src/config.rs
  fuel-core-interfaces/Cargo.toml
  fuel-core/Cargo.toml
  fuel-core/src/args.rs
  fuel-core/src/config.rs
  fuel-core/src/config/chain_config.rs
  fuel-core/src/config/serialization.rs
  fuel-core/src/config/snapshots/fuel_core__config__chain_config__tests__snapshot_configurable_block_height.snap
  fuel-core/src/config/snapshots/fuel_core__config__chain_config__tests__snapshot_contract_with_balances.snap
  fuel-core/src/config/snapshots/fuel_core__config__chain_config__tests__snapshot_contract_with_state.snap
  fuel-core/src/config/snapshots/fuel_core__config__chain_config__tests__snapshot_local_testnet_config.snap
  fuel-core/src/config/snapshots/fuel_core__config__chain_config__tests__snapshot_simple_coin_state.snap
  fuel-core/src/config/snapshots/fuel_core__config__chain_config__tests__snapshot_simple_contract.snap
  fuel-core/src/executor.rs
  fuel-core/src/lib.rs
  fuel-core/src/schema/chain.rs
  fuel-core/src/schema/coin.rs
  fuel-core/src/schema/node_info.rs
  fuel-core/src/schema/tx.rs
  fuel-core/src/service.rs
  fuel-core/src/service/genesis.rs
  fuel-core/src/service/graph_api.rs
  fuel-core/src/service/modules.rs
  fuel-relayer/src/config.rs
  fuel-sync/src/config.rs
  fuel-tests/tests/balances.rs
  fuel-tests/tests/blocks.rs
  fuel-tests/tests/chain.rs
  fuel-tests/tests/coin.rs
  fuel-tests/tests/dap.rs
  fuel-tests/tests/debugger.rs
  fuel-tests/tests/health.rs
  fuel-tests/tests/helpers.rs
  fuel-tests/tests/metrics.rs
  fuel-tests/tests/node_info.rs
  fuel-tests/tests/tx.rs
Labels: enhancement, fuel-core

#452 Fix Clippy
  fuel-core/src/service/modules.rs
  fuel-core/src/state/rocks_db.rs
  fuel-txpool/src/interface.rs
Labels: bug, breaking
