Repository FuelLabs/fuel-core, pull requests merged in 2022-09, with the labels that each got.

#583 Refactored usage of storage traits
  Cargo.lock
  fuel-client/Cargo.toml
  fuel-core-interfaces/Cargo.toml
  fuel-core-interfaces/src/db.rs
  fuel-core-interfaces/src/model/coin.rs
  fuel-core-interfaces/src/relayer.rs
  fuel-core-interfaces/src/signer.rs
  fuel-core-interfaces/src/txpool.rs
  fuel-core/Cargo.toml
  fuel-core/src/coin_query.rs
  fuel-core/src/database.rs
  fuel-core/src/database/balances.rs
  fuel-core/src/database/block.rs
  fuel-core/src/database/code_root.rs
  fuel-core/src/database/coin.rs
  fuel-core/src/database/contracts.rs
  fuel-core/src/database/delegates_index.rs
  fuel-core/src/database/message.rs
  fuel-core/src/database/metadata.rs
  fuel-core/src/database/receipts.rs
  fuel-core/src/database/staking_diffs.rs
  fuel-core/src/database/state.rs
  fuel-core/src/database/storage.rs
  fuel-core/src/database/transaction.rs
  fuel-core/src/database/validator_set.rs
  fuel-core/src/executor.rs
  fuel-core/src/schema/balance.rs
  fuel-core/src/schema/block.rs
  fuel-core/src/schema/chain.rs
  fuel-core/src/schema/coin.rs
  fuel-core/src/schema/contract.rs
  fuel-core/src/schema/message.rs
  fuel-core/src/schema/tx.rs
  fuel-core/src/schema/tx/types.rs
  fuel-core/src/service/genesis.rs
  fuel-core/src/state.rs
  fuel-core/src/state/in_memory.rs
  fuel-core/src/state/in_memory/memory_store.rs
  fuel-core/src/state/in_memory/transaction.rs
  fuel-core/src/state/rocks_db.rs
  fuel-core/src/test_utils.rs
  fuel-relayer/src/mock_db.rs
  fuel-tests/tests/blocks.rs
  fuel-tests/tests/coin.rs
  fuel-txpool/src/containers/dependency.rs
  fuel-txpool/src/mock_db.rs
  fuel-txpool/src/txpool.rs
Labels: enhancement, breaking

#591 Add support of messages into `coinsToSpend`
  fuel-client/assets/schema.sdl
  fuel-client/src/client.rs
  fuel-client/src/client/schema.rs
  fuel-client/src/client/schema/coin.rs
  fuel-client/src/client/schema/message.rs
  fuel-client/src/client/schema/primitives.rs
  fuel-client/src/client/schema/resource.rs
  fuel-client/src/client/schema/snapshots/fuel_gql_client__client__schema__message__tests__owned_message_query_gql_output.snap
  fuel-core/src/chain_config.rs
  fuel-core/src/coin_query.rs
  fuel-core/src/database.rs
  fuel-core/src/database/coin.rs
  fuel-core/src/database/message.rs
  fuel-core/src/database/resource.rs
  fuel-core/src/lib.rs
  fuel-core/src/resource_query.rs
  fuel-core/src/schema.rs
  fuel-core/src/schema/balance.rs
  fuel-core/src/schema/coin.rs
  fuel-core/src/schema/message.rs
  fuel-core/src/schema/resource.rs
  fuel-core/src/schema/scalars.rs
  fuel-core/src/schema/scalars/message_id.rs
  fuel-core/src/service/genesis.rs
  fuel-core/src/state.rs
  fuel-core/src/state/rocks_db.rs
  fuel-core/src/test_utils.rs
  fuel-tests/tests/balances.rs
  fuel-tests/tests/coin.rs
  fuel-tests/tests/lib.rs
  fuel-tests/tests/resource.rs
Labels: breaking, graphql-api

#616 Add `fuel-benches`
  Cargo.lock
  Cargo.toml
  fuel-benches/Cargo.toml
  fuel-benches/benches/vm.rs
  fuel-benches/src/lib.rs
Labels: enhancement

#624 Refactor `FuelBlockHeader::number` to name `da_height` and type `DaBlockHeight`
  fuel-core-interfaces/src/model.rs
  fuel-core-interfaces/src/model/block.rs
  fuel-core-interfaces/src/model/da_block_height.rs
  fuel-core-interfaces/src/relayer.rs
  fuel-core/src/chain_config.rs
  fuel-core/src/chain_config/serialization.rs
  fuel-core/src/cli/run/relayer.rs
  fuel-core/src/database.rs
  fuel-core/src/executor.rs
  fuel-core/src/model.rs
  fuel-core/src/resource_query.rs
  fuel-core/src/schema/message.rs
  fuel-core/src/service/genesis.rs
  fuel-relayer/src/config.rs
  fuel-relayer/src/finalization_queue.rs
  fuel-relayer/src/log.rs
  fuel-relayer/src/pending_blocks.rs
  fuel-relayer/src/relayer.rs
  fuel-relayer/src/validators.rs
  fuel-tests/tests/messages.rs
  fuel-tests/tests/resource.rs
  fuel-tests/tests/snapshot.rs
Labels: breaking, fuel-relayer, tech-debt

#594 Output Bech32Address for initial accounts
  Cargo.lock
  fuel-core/Cargo.toml
  fuel-core/src/chain_config.rs
Labels: enhancement

#632 Support `Message` in the balances API
  Cargo.lock
  fuel-core/src/database/resource.rs
  fuel-core/src/resource_query.rs
  fuel-core/src/schema/balance.rs
  fuel-tests/tests/balances.rs
  fuel-tests/tests/resource.rs
Labels: graphql-api
