Repository FuelLabs/fuel-core, pull requests merged in 2023-06, with the labels that each got.

#1201 Add transaction lifecycle diagram to the docs
  docs/diagrams/tx-lifecycle-june-2023.png
Labels: documentation

#1207 SMT storage key hashing
  Cargo.lock
  Cargo.toml
  bin/e2e-test-client/src/tests/script.rs
  bin/e2e-test-client/src/tests/test_data/large_state/tx.json
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/balances.rs
  crates/fuel-core/src/database/state.rs
  crates/fuel-core/src/database/vm_database.rs
  crates/fuel-core/src/service/genesis.rs
  crates/services/consensus_module/poa/src/service.rs
Labels: breaking

#1232 Remove hybrid PoA block trigger mode
  bin/fuel-core/src/cli/run/consensus.rs
  crates/services/consensus_module/poa/src/config.rs
  crates/services/consensus_module/poa/src/service.rs
  crates/services/consensus_module/poa/src/service_test.rs
  crates/services/consensus_module/poa/src/service_test/trigger_tests.rs
  deployment/charts/templates/fuel-core-deploy.yaml
  deployment/charts/values.yaml
  deployment/scripts/.env
  tests/tests/trigger_integration/hybrid.rs
  tests/tests/trigger_integration/mod.rs
Labels: breaking, fuel-block-producer, tech-debt
