Repository FuelLabs/fuel-core, pull requests merged in 2023-10, with the labels that each got.

#1391 Remove `Result` from streams and use `Batch::is_err`
  Cargo.lock
  crates/services/sync/Cargo.toml
  crates/services/sync/src/import.rs
  crates/services/sync/src/import/tests.rs
  crates/types/src/services/p2p.rs
Labels: no changelog

#1393 Increase heartbeat timeout to one minute
  CHANGELOG.md
  crates/services/p2p/src/heartbeat/handler.rs
Labels: fuel-p2p

#1392 Fix an interger overflow in message_proof when looking beyond genesis
  CHANGELOG.md
  crates/fuel-core/src/query/message.rs
Labels: security, audit-report

#1395 Benchmark {k256, s256, mcpi} opcodes using DependentCost
  CHANGELOG.md
  benches/benches/set/crypto.rs
  benches/benches/set/mem.rs
  benches/benches/set/mod.rs
Labels: fuel-block-executor

#1415 Updated CI to run `cargo update` weekly
  .github/workflows/dependencies.yml
Labels: no changelog

#1416 CI `cargo update` weekly
  .github/workflows/dependencies.yml
Labels: no changelog

#1424 Fix typos
  bin/fuel-core/src/cli/run/p2p.rs
  crates/fuel-core/src/graphql_api/service.rs
  crates/services/p2p/src/heartbeat/handler.rs
  crates/services/p2p/src/request_response/messages.rs
  tests/tests/blocks.rs
Labels: no changelog

#1427 Update benchmarking and collecting for `scwq`, `swwq` and `srwq` opcodes
  benches/benches/vm_set/blockchain.rs
  benches/src/bin/collect.rs
Labels: no changelog

#1429 Rollback modification of the chain specification
  benches/benches/block_target_gas.rs
  deployment/scripts/chainspec/beta_chainspec.json
Labels: no changelog

#1460 chore: fix releasy test tracking branch from `main` to `master`
  .github/workflows/releasy-dependency-commits.yml
  CHANGELOG.md
Labels: bug, ci

#1463 `DB::repair` breaks the table for checkpoints
  .github/workflows/ci.yml
  crates/fuel-core/src/service/adapters/producer.rs
  crates/fuel-core/src/state/rocks_db.rs
  crates/services/p2p/src/config.rs
Labels: no changelog
