Repository FuelLabs/fuel-core, pull requests merged in 2023-02, with the labels that each got.

#968 Add logs to track the listening addresses for the P2P
  bin/fuel-core/src/cli/run/p2p.rs
  crates/services/p2p/src/p2p_service.rs
Labels: fuel-p2p

#974 Fixed bug with disconnection and `max_non_reserved_peers`
  crates/services/p2p/src/p2p_service.rs
  crates/services/p2p/src/peer_manager.rs
Labels: bug, fuel-p2p

#986 make in-memory iteration match rocksdb behavior
  crates/fuel-core/src/state/in_memory/memory_store.rs
Labels: bug

#988 Ignore unpublish changes on standard publish verification
  .github/workflows/ci.yml
Labels: bug

#991 Don't capture signals within lib
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/src/service.rs
  crates/services/src/state.rs
  tests/tests/messages.rs
Labels: bug

#909 Prepare GraphQL For Future Extraction
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/service.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/schema/tx/types.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/sub_services.rs
Labels: graphql-api

#995 revert optimistic reserved node reconnect
  crates/services/p2p/src/heartbeat/handler.rs
  crates/services/p2p/src/p2p_service.rs
  crates/services/p2p/src/peer_manager.rs
Labels: tech-debt, fuel-p2p

#998 make heartbeat config fields configurable and expose them to CLI
  bin/fuel-core/src/cli/run/p2p.rs
  crates/services/p2p/src/config.rs
  crates/services/p2p/src/heartbeat/handler.rs
  crates/services/p2p/src/lib.rs
  crates/services/p2p/src/peer_manager.rs
Labels: enhancement, fuel-p2p

#1002 fix p2p `max_peers_connected_works` test
  crates/services/p2p/src/p2p_service.rs
Labels: bug, fuel-p2p

#1004 Bugfix: set prefix extractor for all columns that need it
  crates/fuel-core/src/schema/coin.rs
  crates/fuel-core/src/schema/contract.rs
  crates/fuel-core/src/schema/message.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/state/rocks_db.rs
  tests/tests/contract.rs
  tests/tests/messages.rs
Labels: bug

#1015 Fix database version serialization
  crates/database/src/lib.rs
  crates/fuel-core/src/database/metadata.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/state/rocks_db.rs
  tests/tests/health.rs
Labels: bug

#1025 Add RUST_LOG option to deployment charts & increase max_transmit_size
  bin/fuel-core/src/cli/run/p2p.rs
  deployment/charts/templates/fuel-core-deploy.yaml
  deployment/charts/values.yaml
  deployment/scripts/.env
Labels: bug

#1027 Disable pagination args for balances
  crates/fuel-core/src/schema/balance.rs
  tests/tests/balances.rs
Labels: graphql-api

#1030 Predicate error handling
  crates/services/txpool/src/test_helpers.rs
  crates/services/txpool/src/txpool.rs
  crates/services/txpool/src/txpool/tests.rs
  crates/types/src/services/txpool.rs
  tests/tests/helpers.rs
  tests/tests/tx/predicates.rs
Labels: enhancement

#1032 Use composite actions
  .github/workflows/ci.yml
Labels: ci

#1041 Added test to verify the iteration over owned transactions
  tests/tests/tx.rs
Labels: graphql-api

#1048 Fixed Tempfile dependency
  Cargo.lock
  Cargo.toml
Labels: bug

#994 Write contract code in raw
  Cargo.lock
  Cargo.toml
  crates/client/src/client/schema/primitives.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/contracts.rs
  crates/fuel-core/src/database/vm_database.rs
  crates/fuel-core/src/state.rs
  crates/fuel-core/src/state/in_memory/memory_store.rs
  crates/fuel-core/src/state/in_memory/transaction.rs
  crates/fuel-core/src/state/rocks_db.rs
  crates/types/src/blockchain/primitives.rs
  tests/tests/messages.rs
Labels: breaking
