Repository FuelLabs/fuel-core, pull requests merged in 2023-12, with the labels that each got.

#1516 feat: Stream data from db, build snapshot incrementally
  Cargo.lock
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli.rs
  bin/fuel-core/src/cli/snapshot.rs
  crates/chain-config/Cargo.toml
  crates/chain-config/src/config.rs
  crates/chain-config/src/config/codec.rs
  crates/chain-config/src/config/codec/decoder.rs
  crates/chain-config/src/config/codec/encoder.rs
  crates/chain-config/src/config/codec/parquet/decode.rs
  crates/chain-config/src/config/codec/parquet/encode.rs
  crates/chain-config/src/config/codec/parquet/schema.rs
  crates/chain-config/src/config/contract_state.rs
  crates/chain-config/src/config/state.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/coin.rs
  crates/fuel-core/src/database/contracts.rs
  crates/fuel-core/src/database/message.rs
  crates/storage/src/lib.rs
  tests/tests/snapshot.rs
Labels: enhancement

#1526 Fix broken link.
  CONTRIBUTING.md
  README.md
  docs/architecture.md
  docs/fee_calculations.md
Labels: no changelog

#1540 fix committed gql schema
  crates/client/assets/schema.sdl
Labels: no changelog

#1543 Fix the example tx in README.md
  README.md
Labels: bug, no changelog

#1558 Update LICENSE
  LICENSE
Labels: no changelog

#1559 Remove duplicating logic in the `KeyValueStore` trait
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/balances.rs
  crates/fuel-core/src/database/block.rs
  crates/fuel-core/src/database/coin.rs
  crates/fuel-core/src/database/contracts.rs
  crates/fuel-core/src/database/message.rs
  crates/fuel-core/src/database/state.rs
  crates/fuel-core/src/database/storage.rs
  crates/fuel-core/src/state.rs
  crates/fuel-core/src/state/in_memory/memory_store.rs
  crates/fuel-core/src/state/in_memory/transaction.rs
  crates/fuel-core/src/state/rocks_db.rs
Labels: no changelog

#1566 Move `KeyValueStore` to the `fuel-core-storage` crate
  crates/database/src/lib.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/block.rs
  crates/fuel-core/src/database/coin.rs
  crates/fuel-core/src/database/contracts.rs
  crates/fuel-core/src/database/message.rs
  crates/fuel-core/src/database/metadata.rs
  crates/fuel-core/src/database/transaction.rs
  crates/fuel-core/src/database/transactions.rs
  crates/fuel-core/src/service/adapters/executor.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/adapters/txpool.rs
  crates/fuel-core/src/state.rs
  crates/fuel-core/src/state/in_memory/memory_store.rs
  crates/fuel-core/src/state/in_memory/transaction.rs
  crates/fuel-core/src/state/rocks_db.rs
  crates/storage/src/iter.rs
  crates/storage/src/kv_store.rs
  crates/storage/src/lib.rs
Labels: no changelog

#1379 Update `libp2p` from `0.50.0` to `0.53.1`
  Cargo.lock
  Cargo.toml
  crates/fuel-core/src/p2p_test_helpers.rs
  crates/fuel-core/src/service/adapters/producer.rs
  crates/metrics/Cargo.toml
  crates/metrics/src/p2p_metrics.rs
  crates/metrics/src/response.rs
  crates/services/p2p/Cargo.toml
  crates/services/p2p/src/behavior.rs
  crates/services/p2p/src/codecs.rs
  crates/services/p2p/src/codecs/postcard.rs
  crates/services/p2p/src/config.rs
  crates/services/p2p/src/config/fuel_authenticated.rs
  crates/services/p2p/src/config/fuel_upgrade.rs
  crates/services/p2p/src/discovery.rs
  crates/services/p2p/src/discovery/discovery_config.rs
  crates/services/p2p/src/discovery/mdns.rs
  crates/services/p2p/src/gossipsub/config.rs
  crates/services/p2p/src/heartbeat.rs
  crates/services/p2p/src/heartbeat/handler.rs
  crates/services/p2p/src/lib.rs
  crates/services/p2p/src/p2p_service.rs
  crates/services/p2p/src/peer_manager.rs
  crates/services/p2p/src/peer_report.rs
  crates/services/p2p/src/request_response/messages.rs
  crates/services/p2p/src/service.rs
Labels: no changelog
