Repository FuelLabs/fuel-core, pull requests merged in 2024-11, with the labels that each got.

#2389 Return reason of why proof cant be generated (api change)
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema/message.rs
  crates/fuel-core/src/schema/message.rs
  tests/tests/messages.rs
  tests/tests/regenesis.rs
Labels: breaking

#2390 Add test node herself in reserved nodes.
  crates/services/p2p/src/p2p_service.rs
Labels: no changelog

#2352 fix(p2p): cache responses to serve without roundtrip to db
  CHANGELOG.md
  Cargo.lock
  crates/metrics/src/p2p_metrics.rs
  crates/services/p2p/Cargo.toml
  crates/services/p2p/src/cached_view.rs
  crates/services/p2p/src/lib.rs
  crates/services/p2p/src/service.rs
Labels: fuel-p2p

#2444 Fix codeowners
  .github/CODEOWNERS
Labels: no changelog

#2415 Allow DA recorded blocks to come out-of-order
  Cargo.lock
  crates/fuel-gas-price-algorithm/Cargo.toml
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/charts.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_da_record_data_tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_l2_block_data_tests.rs
  crates/services/gas_price_service/src/v1/da_source_service.rs
  crates/services/gas_price_service/src/v1/da_source_service/block_committer_costs.rs
  crates/services/gas_price_service/src/v1/metadata.rs
  crates/services/gas_price_service/src/v1/service.rs
Labels: no changelog

#2467 fix: Add missing features to `fuel-core-tests`
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
  .github/workflows/docker-images.yml
  .github/workflows/publish-codecov.yml
  ci_checks.sh
  crates/fuel-core/src/state/rocks_db.rs
  crates/services/gas_price_service/src/v1/da_source_service/block_committer_costs.rs
  deployment/Dockerfile
  deployment/e2e-client.Dockerfile
  rust-toolchain.toml
  tests/tests/messages.rs
  tests/tests/node_info.rs
  tests/tests/poa.rs
Labels: bug, no changelog
