Repository FuelLabs/fuel-core, pull requests merged in 2024-02, with the labels that each got.

#1636 Add docs for GraphQL DAP endpoints
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/fuel-core/src/schema/dap.rs
Labels: documentation, graphql-api

#1631 feat: dry run multiple transactions
  CHANGELOG.md
  bin/e2e-test-client/src/lib.rs
  bin/e2e-test-client/src/tests/script.rs
  bin/fuel-core-client/src/main.rs
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__tx__tests__dry_run_tx_gql_output.snap
  crates/client/src/client/schema/tx.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/schema/tx/types.rs
  crates/fuel-core/src/service/adapters/executor.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/adapters/producer.rs
  crates/services/executor/src/executor.rs
  crates/services/producer/src/block_producer.rs
  crates/services/producer/src/ports.rs
  tests/tests/tx.rs
  tests/tests/tx/utxo_validation.rs
Labels: enhancement, graphql-api

#1574 Decrease peer reputation on request timeouts and decode errors
  CHANGELOG.md
  crates/services/p2p/src/behavior.rs
  crates/services/p2p/src/p2p_service.rs
  crates/services/p2p/src/request_response/messages.rs
  crates/services/p2p/src/service.rs
Labels: fuel-p2p

#1656 Bump up rust to 1.75
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
  ci_checks.sh
  deployment/Dockerfile
  deployment/e2e-client.Dockerfile
Labels: no changelog

#1692 Remove failing deployment job
  .github/workflows/ci.yml
Labels: no changelog

#1691 chore: format cargo tomls and add ci check
  .github/workflows/ci.yml
  .prettierrc
  Cargo.toml
  benches/Cargo.toml
  benches/benches-outputs/Cargo.toml
  bin/e2e-test-client/Cargo.toml
  bin/fuel-core-client/Cargo.toml
  bin/fuel-core/Cargo.toml
  ci_checks.sh
  crates/chain-config/Cargo.toml
  crates/client/Cargo.toml
  crates/database/Cargo.toml
  crates/fuel-core/Cargo.toml
  crates/services/executor/Cargo.toml
  crates/services/p2p/Cargo.toml
  crates/services/relayer/Cargo.toml
  crates/services/txpool/Cargo.toml
  crates/storage/Cargo.toml
  crates/trace/Cargo.toml
  crates/types/Cargo.toml
  tests/Cargo.toml
  tests/test-helpers/Cargo.toml
  version-compatibility/0.14.1-0.15.0/fuel-core-0.14.1-client-0.15.0/Cargo.toml
  version-compatibility/0.14.1-0.15.0/fuel-core-0.15.0-client-0.14.1/Cargo.toml
  version-compatibility/Cargo.toml
  xtask/Cargo.toml
Labels: tech-debt, no changelog
