Repository FuelLabs/fuel-core, pull requests merged in 2024-08, with the labels that each got.

#2052 feat: add chain config to Docker images
  deployment/Dockerfile
Labels: no changelog

#1988 Blob tx support and fuel-vm 0.56.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  benches/benches-outputs/src/lib.rs
  benches/benches/block_target_gas_set/contract.rs
  benches/benches/block_target_gas_set/crypto.rs
  benches/benches/vm_set/blockchain.rs
  benches/benches/vm_set/crypto.rs
  benches/src/bin/collect.rs
  benches/src/default_gas_costs.rs
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  bin/fuel-core/chainspec/local-testnet/state_config.json
  bin/fuel-core/chainspec/local-testnet/state_transition_bytecode.wasm
  bin/fuel-core/src/cli/snapshot.rs
  crates/chain-config/src/config.rs
  crates/chain-config/src/config/blob.rs
  crates/chain-config/src/config/randomize.rs
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/chain-config/src/config/state.rs
  crates/chain-config/src/config/state/snapshots/fuel_core_chain_config__config__state__writer__tests__json_snapshot_is_human_readable.snap
  crates/chain-config/src/config/state/writer.rs
  crates/client/assets/schema.sdl
  crates/client/src/client/schema/chain.rs
  crates/client/src/client/schema/primitives.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__chain__tests__chain_gql_query_output.snap
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__tx__tests__transparent_transaction_by_id_query_gql_output.snap
  crates/client/src/client/schema/tx/transparent_tx.rs
  crates/client/src/client/types/gas_costs.rs
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/fuel-core/src/schema/chain.rs
  crates/fuel-core/src/schema/dap.rs
  crates/fuel-core/src/schema/scalars.rs
  crates/fuel-core/src/schema/tx/types.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/exporter.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/on_chain.rs
  crates/services/executor/src/executor.rs
  crates/services/executor/src/ports.rs
  crates/services/txpool/src/txpool.rs
  crates/storage/src/column.rs
  crates/storage/src/structured_storage.rs
  crates/storage/src/structured_storage/blobs.rs
  crates/storage/src/vm_storage.rs
  crates/types/src/lib.rs
  crates/types/src/services/txpool.rs
  tests/tests/blob.rs
  tests/tests/lib.rs
  tests/tests/local_node.rs
  tests/tests/regenesis.rs
Labels: breaking

#2056 Bug/fix gas price metadata sync
  Cargo.lock
  crates/fuel-core/src/service/sub_services/algorithm_updater.rs
  tests/Cargo.toml
  tests/tests/recovery.rs
Labels: no changelog

#2075 fix: Rename `e2e-client` test crate to `fuel-core-e2e-client` and rem…
  bin/e2e-test-client/Cargo.toml
Labels: no changelog

#2077 chore(github): clean up PR template
  .github/pull_request_template.md
Labels: no changelog

#2085 Addressed comments in the unknown columns PR
  crates/fuel-core/src/state/rocks_db.rs
Labels: no changelog

#2090 Remove RUSTSEC-2023-0052 from ignored errors as it's fixed now
  .cargo/audit.toml
Labels: no changelog

#2080 Validate WASM on txpool level before allowing upgrade tx
  CHANGELOG.md
  Cargo.lock
  bin/fuel-core/chainspec/local-testnet/state_transition_bytecode.wasm
  crates/fuel-core/src/service/adapters/block_importer.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/txpool/src/ports.rs
  crates/services/txpool/src/service.rs
  crates/services/txpool/src/service/test_helpers.rs
  crates/services/txpool/src/test_helpers.rs
  crates/services/txpool/src/txpool.rs
  crates/services/txpool/src/txpool/tests.rs
  crates/services/upgradable-executor/Cargo.toml
  crates/services/upgradable-executor/src/error.rs
  crates/services/upgradable-executor/src/executor.rs
  crates/services/upgradable-executor/src/lib.rs
  crates/types/src/services/txpool.rs
  tests/tests/tx/upgrade.rs
Labels: breaking, fuel-txpool, wasm

#2066 feat: publish to public ECR repo
  .github/workflows/ci.yml
Labels: no changelog

#2072 doc: refine the transaction example in the README
  README.md
Labels: no changelog

#2051 AWS KMS block signing support and Rust 1.79
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
  CHANGELOG.md
  Cargo.lock
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli/run.rs
  ci_checks.sh
  crates/chain-config/src/config/snapshot_metadata.rs
  crates/fuel-core/src/p2p_test_helpers.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/fuel-core/src/state/rocks_db.rs
  crates/services/consensus_module/poa/Cargo.toml
  crates/services/consensus_module/poa/src/config.rs
  crates/services/consensus_module/poa/src/lib.rs
  crates/services/consensus_module/poa/src/ports.rs
  crates/services/consensus_module/poa/src/service.rs
  crates/services/consensus_module/poa/src/service_test.rs
  crates/services/consensus_module/poa/src/service_test/manually_produce_tests.rs
  crates/services/consensus_module/poa/src/service_test/trigger_tests.rs
  crates/services/consensus_module/poa/src/signer.rs
  crates/services/p2p/src/discovery/discovery_config.rs
  crates/services/sync/src/lib.rs
  crates/services/txpool/src/service/update_sender/tests/test_e2e.rs
  deployment/Dockerfile
  rust-toolchain.toml
  tests/Cargo.toml
  tests/test-helpers/src/fuel_core_driver.rs
  tests/tests/blocks.rs
  tests/tests/kms.rs
  tests/tests/poa.rs
  tests/tests/trigger_integration/instant.rs
  tests/tests/trigger_integration/interval.rs
  tests/tests/trigger_integration/never.rs
  version-compatibility/forkless-upgrade/src/tests_helper.rs
Labels: fuel-block-producer, security

#2103 Small improvements for tests to make them more stable
  crates/fuel-gas-price-algorithm/src/v0/tests/algorithm_v0_tests.rs
  crates/services/producer/src/block_producer.rs
  crates/services/sync/src/import/back_pressure_tests.rs
  tests/tests/recovery.rs
Labels: no changelog

#2089 Bump wasmtime version
  Cargo.lock
  crates/services/upgradable-executor/Cargo.toml
Labels: dependencies, no changelog

#2110 Change TODO clippy to wait for false positive correction
  crates/chain-config/src/config/snapshot_metadata.rs
Labels: no changelog

#2123 chore(p2p_service): remove unnecessary cast to usize
  bin/fuel-core/src/cli/run/p2p.rs
  crates/services/p2p/src/config.rs
  crates/services/p2p/src/service.rs
Labels: no changelog

#2127 Added a benchmark for the predicate with ed19 verification
  benches/benches/transaction_throughput.rs
  tests/test-helpers/src/builder.rs
Labels: no changelog

#2119 feat: Add graphql query fields for retreiving information about upgrades
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema.rs
  crates/client/src/client/schema/upgrades.rs
  crates/client/src/client/types.rs
  crates/client/src/client/types/upgrades.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/query.rs
  crates/fuel-core/src/query/block.rs
  crates/fuel-core/src/query/upgrades.rs
  crates/fuel-core/src/schema.rs
  crates/fuel-core/src/schema/chain.rs
  crates/fuel-core/src/schema/upgrades.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  tests/tests/tx/upgrade.rs
Labels: graphql-api

#2120 feat: add `submitAndAwaitStatus` subscription endpoint
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema/tx.rs
  crates/fuel-core/src/schema/tx.rs
  tests/tests/tx.rs
Labels: graphql-api

#2134 Secp256k1 RecoveryID correction for KMS-genrated signatures
  CHANGELOG.md
  bin/fuel-core/src/cli/run.rs
  crates/services/consensus_module/poa/src/signer.rs
  tests/tests/poa.rs
Labels: bug
