Repository FuelLabs/fuel-core, pull requests merged in 2024-05, with the labels that each got.

#1848 feat: Support block and header versions gql
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema/block.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__block__tests__block_by_height_query_gql_output.snap
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__block__tests__block_by_id_query_gql_output.snap
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__block__tests__blocks_connection_query_gql_output.snap
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__chain__tests__chain_gql_query_output.snap
  crates/client/src/client/types/block.rs
  crates/client/src/client/types/chain_info.rs
  crates/client/src/client/types/message.rs
  crates/fuel-core/src/schema/block.rs
  crates/types/src/blockchain/block.rs
  crates/types/src/blockchain/header.rs
Labels: breaking

#1891 feat: Preserve message proofs post-regenesis
  CHANGELOG.md
  bin/fuel-core/src/cli/snapshot.rs
  crates/chain-config/src/config/state.rs
  crates/chain-config/src/config/state/snapshots/fuel_core_chain_config__config__state__writer__tests__json_snapshot_is_human_readable.snap
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/exporter.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/on_chain.rs
  tests/tests/regenesis.rs
  tests/tests/snapshot.rs
Labels: regenesis

#1900 chore: update README fuel-core run options
  CHANGELOG.md
  README.md
Labels: documentation
