Repository FuelLabs/fuel-core, pull requests merged in 2024-06, with the labels that each got.

#1930 Fixed logging of the WASM executor
  crates/services/upgradable-executor/src/executor.rs
Labels: no changelog

#1932 Document wasm toolchain installation, add rust-toolchain.toml
  README.md
  rust-toolchain.toml
Labels: no changelog

#1924 Add optional `gas_price` argument to `dry_run_opt`
  CHANGELOG.md
  bin/e2e-test-client/src/tests/script.rs
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__tx__tests__dry_run_tx_gql_output.snap
  crates/client/src/client/schema/tx.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/services/producer/src/block_producer.rs
  tests/tests/gas_price.rs
  tests/tests/tx/utxo_validation.rs
Labels: tech-debt

#1888 Reuse VM memory across executions
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  benches/benches/block_target_gas.rs
  benches/benches/transaction_throughput.rs
  benches/benches/vm.rs
  benches/benches/vm_initialization.rs
  benches/benches/vm_set/blockchain.rs
  benches/src/lib.rs
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/executor.rs
  crates/fuel-core/src/graphql_api/api_service.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/schema/dap.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/txpool.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/fuel-core/src/service/vm_pool.rs
  crates/services/executor/src/executor.rs
  crates/services/txpool/Cargo.toml
  crates/services/txpool/src/ports.rs
  crates/services/txpool/src/service.rs
  crates/services/txpool/src/service/test_helpers.rs
  crates/services/txpool/src/test_helpers.rs
  crates/services/txpool/src/txpool.rs
  crates/services/txpool/src/txpool/tests.rs
  crates/types/src/lib.rs
  tests/tests/tx/predicates.rs
  tests/tests/tx/txn_status_subscription.rs
Labels: enhancement, fuel-block-executor

#1915 Fixed reconnection issue in the dev cluster with AWS cluster
  CHANGELOG.md
  bin/fuel-core/src/cli/run/p2p.rs
  crates/services/p2p/src/behavior.rs
  crates/services/p2p/src/config.rs
  crates/services/p2p/src/config/connection_tracker.rs
  crates/services/p2p/src/config/fuel_authenticated.rs
  crates/services/p2p/src/config/guarded_node.rs
  crates/services/p2p/src/p2p_service.rs
  crates/services/p2p/src/peer_manager.rs
  crates/services/p2p/src/peer_report.rs
Labels: breaking

#1943 Fix code coverage compilation and tests
  .cargo/config.toml
  crates/chain-config/src/config/contract.rs
  crates/fuel-core/src/database/state.rs
  crates/services/upgradable-executor/build.rs
  crates/services/upgradable-executor/src/executor.rs
  tests/tests/blocks.rs
  tests/tests/poa.rs
  tests/tests/sync.rs
Labels: no changelog

#1954 deps(client): update eventsource-client to fix CVE(s)
  Cargo.lock
  crates/client/Cargo.toml
Labels: no changelog

#1975 Use `fuel-vm 0.54.0`
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  benches/benches-outputs/src/lib.rs
  benches/benches/vm_set/mem.rs
  benches/src/bin/collect.rs
  benches/src/default_gas_costs.rs
  bin/fuel-core/chainspec/local-testnet/README.md
  bin/fuel-core/chainspec/local-testnet/benchmarks_fuel_core_0_28_0.json
  bin/fuel-core/chainspec/local-testnet/benchmarks_fuel_core_0_30_0.json
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  bin/fuel-core/chainspec/local-testnet/state_transition_bytecode.wasm
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/client/assets/schema.sdl
  crates/client/src/client/schema/chain.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__chain__tests__chain_gql_query_output.snap
  crates/client/src/client/types/gas_costs.rs
  crates/fuel-core/src/schema/chain.rs
  crates/fuel-core/src/schema/tx/types.rs
Labels: breaking

#1947 Generate and publish code coverage reports in the CI
  .github/workflows/ci.yml
  .github/workflows/scripts/generate_pages_index.py
  tests/tests/sync.rs
  tests/tests/tx_gossip.rs
Labels: no changelog

#1986 Use companies fork of the `publish-crates` action
  .github/workflows/ci.yml
Labels: no changelog

#1989 Extract `HistoricalView` trait from the `AtomicView`
  CHANGELOG.md
  bin/fuel-core/chainspec/local-testnet/state_transition_bytecode.wasm
  crates/fuel-core/src/coins_query.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/database_description.rs
  crates/fuel-core/src/executor.rs
  crates/fuel-core/src/graphql_api/api_service.rs
  crates/fuel-core/src/graphql_api/database.rs
  crates/fuel-core/src/graphql_api/database/arc_wrapper.rs
  crates/fuel-core/src/graphql_api/view_extension.rs
  crates/fuel-core/src/schema/dap.rs
  crates/fuel-core/src/service/adapters/producer.rs
  crates/fuel-core/src/service/adapters/relayer.rs
  crates/services/consensus_module/src/block_verifier.rs
  crates/services/executor/src/executor.rs
  crates/services/importer/src/importer.rs
  crates/services/importer/src/ports.rs
  crates/services/p2p/src/service.rs
  crates/services/producer/src/block_producer.rs
  crates/services/producer/src/mocks.rs
  crates/services/producer/src/ports.rs
  crates/services/txpool/src/mock_db.rs
  crates/services/txpool/src/service.rs
  crates/services/txpool/src/txpool.rs
  crates/services/upgradable-executor/src/executor.rs
  crates/storage/src/lib.rs
  crates/storage/src/structured_storage.rs
  crates/storage/src/transactional.rs
Labels: breaking
