Repository FuelLabs/fuel-core, pull requests merged in 2024-03, with the labels that each got.

#1728 Use a right version of the release `0.23.0`
  Cargo.lock
  Cargo.toml
  deployment/charts/Chart.yaml
Labels: no changelog

#1737 Remove genesis temp tables
  CHANGELOG.md
  crates/fuel-core/src/database/genesis_progress.rs
  crates/fuel-core/src/database/storage.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/workers.rs
  crates/services/executor/src/refs/contract.rs
Labels: tech-debt, regenesis

#1781 Removed the usage of the `lazy_static` from teh codebase
  Cargo.lock
  Cargo.toml
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli.rs
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/snapshot.rs
  crates/services/upgradable-executor/Cargo.toml
  crates/services/upgradable-executor/src/executor.rs
  crates/services/upgradable-executor/src/lib.rs
Labels: no changelog

#1788 Fixed flaky test
  crates/fuel-core/src/service/genesis/runner.rs
Labels: no changelog

#1786 feat: Add some off chain tables to regenesis
  CHANGELOG.md
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli/snapshot.rs
  crates/chain-config/src/config/state.rs
  crates/chain-config/src/config/state/reader.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/genesis_progress.rs
  crates/fuel-core/src/database/transactions.rs
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/graphql_api/storage/transactions.rs
  crates/fuel-core/src/p2p_test_helpers.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/off_chain.rs
  crates/fuel-core/src/service/genesis/on_chain.rs
  crates/fuel-core/src/service/genesis/runner.rs
  crates/fuel-core/src/service/genesis/workers.rs
  crates/fuel-core/src/service/sub_services.rs
Labels: enhancement

#1792 Moved chain specification into `fuel-core-bin` crate
  bin/e2e-test-client/tests/integration_tests.rs
  bin/fuel-core/chainspec/README.md
  bin/fuel-core/chainspec/dev-testnet/chain_config.json
  bin/fuel-core/chainspec/dev-testnet/metadata.json
  bin/fuel-core/chainspec/dev-testnet/state_config.json
  bin/fuel-core/chainspec/testnet/chain_config.json
  bin/fuel-core/chainspec/testnet/metadata.json
  bin/fuel-core/chainspec/testnet/state_config.json
  bin/fuel-core/src/cli.rs
  tests/tests/deployment.rs
Labels: no changelog
