Repository FuelLabs/fuel-core, pull requests merged in 2024-01, with the labels that each got.

#1586 Remove RustSec Ignore for RUSTSEC-2022-0093
  .cargo/audit.toml
Labels: no changelog

#1573 Simplify p2p request/response message serialization
  CHANGELOG.md
  crates/services/p2p/src/behavior.rs
  crates/services/p2p/src/codecs.rs
  crates/services/p2p/src/codecs/postcard.rs
  crates/services/p2p/src/p2p_service.rs
  crates/services/p2p/src/request_response/messages.rs
  crates/services/p2p/src/service.rs
Labels: fuel-p2p

#1603 Switch katyo/publish-crates@v2 to xgreenx/publish-crates@v1 for the CI
  .github/workflows/ci.yml
Labels: no changelog

#1601 Fix cargo doc, check for cargo doc in the CI
  .github/workflows/ci.yml
  CHANGELOG.md
  bin/e2e-test-client/src/config.rs
  crates/fuel-core/src/coins_query.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/storage.rs
  crates/fuel-core/src/service.rs
  crates/services/p2p/src/config.rs
  crates/services/p2p/src/gossipsub/messages.rs
  crates/services/p2p/src/p2p_service.rs
  crates/services/relayer/src/service.rs
  crates/services/src/service.rs
  crates/storage/src/tables.rs
  crates/types/src/blockchain/consensus/poa.rs
  crates/types/src/blockchain/header.rs
  crates/types/src/services/executor.rs
  crates/types/src/services/p2p.rs
Labels: tech-debt, ci

#1576 Move storage traits implementation to the `fuel-core-storage` crate
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ci_checks.sh
  crates/chain-config/Cargo.toml
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/balances.rs
  crates/fuel-core/src/database/block.rs
  crates/fuel-core/src/database/code_root.rs
  crates/fuel-core/src/database/coin.rs
  crates/fuel-core/src/database/contracts.rs
  crates/fuel-core/src/database/message.rs
  crates/fuel-core/src/database/metadata.rs
  crates/fuel-core/src/database/receipts.rs
  crates/fuel-core/src/database/relayer.rs
  crates/fuel-core/src/database/sealed_block.rs
  crates/fuel-core/src/database/state.rs
  crates/fuel-core/src/database/storage.rs
  crates/fuel-core/src/database/transaction.rs
  crates/fuel-core/src/database/transactions.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters/executor.rs
  crates/fuel-core/src/state.rs
  crates/fuel-core/src/state/in_memory/transaction.rs
  crates/services/executor/src/executor.rs
  crates/services/executor/src/ports.rs
  crates/services/relayer/Cargo.toml
  crates/services/relayer/src/ports.rs
  crates/storage/Cargo.toml
  crates/storage/src/blueprint.rs
  crates/storage/src/blueprint/plain.rs
  crates/storage/src/blueprint/sparse.rs
  crates/storage/src/codec.rs
  crates/storage/src/codec/manual.rs
  crates/storage/src/codec/postcard.rs
  crates/storage/src/codec/primitive.rs
  crates/storage/src/codec/raw.rs
  crates/storage/src/column.rs
  crates/storage/src/kv_store.rs
  crates/storage/src/lib.rs
  crates/storage/src/structured_storage.rs
  crates/storage/src/structured_storage/balances.rs
  crates/storage/src/structured_storage/blocks.rs
  crates/storage/src/structured_storage/coins.rs
  crates/storage/src/structured_storage/contracts.rs
  crates/storage/src/structured_storage/merkle_data.rs
  crates/storage/src/structured_storage/messages.rs
  crates/storage/src/structured_storage/receipts.rs
  crates/storage/src/structured_storage/sealed_block.rs
  crates/storage/src/structured_storage/state.rs
  crates/storage/src/structured_storage/transactions.rs
  crates/storage/src/tables.rs
  crates/types/Cargo.toml
  crates/types/src/blockchain/header.rs
  crates/types/src/blockchain/primitives.rs
  crates/types/src/entities/coins/coin.rs
  crates/types/src/lib.rs
Labels: breaking

#1610 Applying comments from the PR for the storage crate
  crates/fuel-core/src/database/transactions.rs
  crates/storage/src/blueprint.rs
  crates/storage/src/blueprint/plain.rs
  crates/storage/src/blueprint/sparse.rs
  crates/storage/src/codec/manual.rs
  crates/storage/src/codec/postcard.rs
  crates/storage/src/codec/raw.rs
  crates/storage/src/kv_store.rs
  crates/storage/src/lib.rs
  crates/storage/src/structured_storage.rs
Labels: no changelog

#1613 feat: add api endpoint to retrieve messages by nonce
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema/message.rs
  crates/fuel-core/src/schema/message.rs
  tests/tests/messages.rs
Labels: enhancement

#1617 Update Docker tags for Flux integration
  .github/workflows/ci.yml
Labels: no changelog

#1614 Remove dev consensus key
  CHANGELOG.md
  bin/fuel-core/src/cli/run.rs
Labels: breaking, tech-debt
