Repository FuelLabs/fuel-core, pull requests merged in 2024-10, with the labels that each got.

#2256 chore(gas_price_service): split into v0 and v1 and squash FuelGasPriceUpdater type into GasPriceService
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/database_description/gas_price.rs
  crates/fuel-core/src/service/adapters/fuel_gas_price_provider.rs
  crates/fuel-core/src/service/adapters/fuel_gas_price_provider/tests/producer_gas_price_tests.rs
  crates/fuel-core/src/service/adapters/fuel_gas_price_provider/tests/tx_pool_gas_price_tests.rs
  crates/fuel-core/src/service/adapters/gas_price_adapters.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/gas_price_service/src/common.rs
  crates/services/gas_price_service/src/common/fuel_core_storage_adapter.rs
  crates/services/gas_price_service/src/common/fuel_core_storage_adapter/metadata_tests.rs
  crates/services/gas_price_service/src/common/fuel_core_storage_adapter/storage.rs
  crates/services/gas_price_service/src/common/gas_price_algorithm.rs
  crates/services/gas_price_service/src/common/l2_block_source.rs
  crates/services/gas_price_service/src/common/l2_block_source/tests.rs
  crates/services/gas_price_service/src/common/updater_metadata.rs
  crates/services/gas_price_service/src/common/utils.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater/algorithm_updater.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater/tests.rs
  crates/services/gas_price_service/src/lib.rs
  crates/services/gas_price_service/src/ports.rs
  crates/services/gas_price_service/src/static_updater.rs
  crates/services/gas_price_service/src/v0.rs
  crates/services/gas_price_service/src/v0/algorithm.rs
  crates/services/gas_price_service/src/v0/metadata.rs
  crates/services/gas_price_service/src/v0/service.rs
  crates/services/gas_price_service/src/v0/tests.rs
  crates/services/gas_price_service/src/v0/uninitialized_task.rs
  crates/services/gas_price_service/src/v1.rs
  crates/services/gas_price_service/src/v1/algorithm.rs
  crates/services/gas_price_service/src/v1/da_source_adapter.rs
  crates/services/gas_price_service/src/v1/da_source_adapter/block_committer_costs.rs
  crates/services/gas_price_service/src/v1/da_source_adapter/dummy_costs.rs
  crates/services/gas_price_service/src/v1/da_source_adapter/service.rs
  tests/tests/gas_price.rs
Labels: no changelog

#2252 Use bytes from `unrecorded_blocks` rather from the block from DA
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/charts.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/src/v0.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_da_record_data_tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_l2_block_data_tests.rs
Labels: no changelog

#2278 fix(da_block_costs): remove Arc<Mutex<>> on shared_state and expose channel
  crates/services/gas_price_service/src/v1.rs
  crates/services/gas_price_service/src/v1/da_source_adapter.rs
  crates/services/gas_price_service/src/v1/da_source_service.rs
  crates/services/gas_price_service/src/v1/da_source_service/block_committer_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/dummy_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/service.rs
Labels: no changelog

#2272 fix(combined_database): syncing auxiliary databases on startup with custom behaviour
  crates/fuel-core/src/combined_database.rs
Labels: no changelog

#2285 [v0.36.0] fix: Manually encode Authorization header for eventsource_client
  Cargo.lock
  crates/client/Cargo.toml
  crates/client/src/client.rs
Labels: no changelog

#2284 fix: Manually encode Authorization header for eventsource_client
  Cargo.lock
  crates/client/Cargo.toml
  crates/client/src/client.rs
Labels: no changelog

#2290 Address `async-graphql` vulnerability
  CHANGELOG.md
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/run/graphql.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/graphql_api.rs
  crates/fuel-core/src/graphql_api/api_service.rs
  crates/fuel-core/src/service/config.rs
Labels: no changelog

#2271 Update the WASM compatibility tests for `0.36` release
  version-compatibility/forkless-upgrade/Cargo.toml
  version-compatibility/forkless-upgrade/chain-configurations/v36/README.md
  version-compatibility/forkless-upgrade/chain-configurations/v36/chain_config.json
  version-compatibility/forkless-upgrade/chain-configurations/v36/metadata.json
  version-compatibility/forkless-upgrade/chain-configurations/v36/state_config.json
  version-compatibility/forkless-upgrade/chain-configurations/v36/state_transition_bytecode.wasm
  version-compatibility/forkless-upgrade/src/backward_compatibility.rs
  version-compatibility/forkless-upgrade/src/forward_compatibility.rs
  version-compatibility/forkless-upgrade/src/lib.rs
  version-compatibility/forkless-upgrade/src/tests_helper.rs
Labels: no changelog

#1609 DA compression
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli/run.rs
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema.rs
  crates/client/src/client/schema/da_compressed.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__da_compressed__tests__block_by_height_query_gql_output.snap
  crates/compression/Cargo.toml
  crates/compression/README.md
  crates/compression/src/compress.rs
  crates/compression/src/config.rs
  crates/compression/src/decompress.rs
  crates/compression/src/eviction_policy.rs
  crates/compression/src/lib.rs
  crates/compression/src/ports.rs
  crates/compression/src/registry.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/graphql_api.rs
  crates/fuel-core/src/graphql_api/da_compression.rs
  crates/fuel-core/src/graphql_api/database.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/graphql_api/storage/da_compression.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/evictor_cache.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/predicate_code_codec.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/reverse_key.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/script_code_codec.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/timestamps.rs
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/fuel-core/src/graphql_api/worker_service/tests.rs
  crates/fuel-core/src/p2p_test_helpers.rs
  crates/fuel-core/src/query.rs
  crates/fuel-core/src/query/da_compressed.rs
  crates/fuel-core/src/query/message/test.rs
  crates/fuel-core/src/schema.rs
  crates/fuel-core/src/schema/da_compressed.rs
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/storage/Cargo.toml
  crates/storage/src/lib.rs
  crates/types/Cargo.toml
  crates/types/src/blockchain/block.rs
  crates/types/src/blockchain/header.rs
  crates/types/src/blockchain/primitives.rs
  crates/types/src/lib.rs
  tests/Cargo.toml
  tests/tests/da_compression.rs
  tests/tests/lib.rs
  tests/tests/node_info.rs
Labels: mainnet

#2301 Use different port for every version compatibility test
  version-compatibility/forkless-upgrade/src/backward_compatibility.rs
Labels: no changelog

#2292 Updates to price algorithm
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
Labels: no changelog

#2308 fix(p2p): useless dials to reserved nodes which dont have a location multiaddress
  crates/services/p2p/src/discovery/discovery_config.rs
  crates/services/p2p/src/gossipsub/config.rs
  crates/services/p2p/src/lib.rs
  crates/services/p2p/src/peer_report.rs
  crates/services/p2p/src/utils.rs
Labels: no changelog

#2311 chore(executor): instrument errors to be more meaningful
  crates/fuel-core/src/executor.rs
  crates/services/executor/src/executor.rs
  crates/types/src/services/executor.rs
Labels: no changelog

#2316 fix(txpool): Error in GossipsubMessageAcceptance variant docstrings
  crates/types/src/services/p2p.rs
Labels: no changelog

#2325 refactor: Eager returns in txpool_v2::service::Task::run
  crates/services/txpool_v2/src/service.rs
Labels: no changelog

#2320 fix(api_service): exclude health checks from throttling with ConcurrencyLimitLayer
  CHANGELOG.md
  crates/fuel-core/src/graphql_api/api_service.rs
  tests/tests/dos.rs
Labels: bug

#2293 Remove the `normalize_rewards_and_costs()` function
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_da_record_data_tests.rs
Labels: no changelog

#2322 fix(genesis): set salt of contract on execution of genesis state configuration
  CHANGELOG.md
  crates/client/src/client.rs
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/graphql_api/storage/contracts.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/off_chain.rs
  tests/tests/contract.rs
Labels: bug

#2317 fix(gas_price_service): service name and unused trait impl
  crates/services/gas_price_service/src/v0/service.rs
  crates/services/gas_price_service/src/v0/uninitialized_task.rs
Labels: no changelog

#2342 Do not require build of docker images to pass CI
  .github/workflows/ci.yml
Labels: no changelog

#2353 Disable flaky `test_poa_multiple_producers` test
  crates/services/src/async_processor.rs
  crates/services/src/sync_processor.rs
  tests/tests/poa.rs
Labels: no changelog

#2310 Add more metrics
  CHANGELOG.md
  Cargo.lock
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/src/service/adapters/block_importer.rs
  crates/fuel-core/src/service/config.rs
  crates/metrics/Cargo.toml
  crates/metrics/src/buckets.rs
  crates/metrics/src/config.rs
  crates/metrics/src/futures/future_tracker.rs
  crates/metrics/src/graphql_metrics.rs
  crates/metrics/src/importer.rs
  crates/metrics/src/lib.rs
  crates/services/importer/src/config.rs
  crates/services/importer/src/importer.rs
  crates/services/p2p/Cargo.toml
  crates/services/p2p/src/p2p_service.rs
  crates/types/src/services/executor.rs
Labels: breaking

#2363 Add documentation to run a ignition node in readme
  README.md
Labels: no changelog

#2258 Return reason of why proof cant be generated
  crates/fuel-core/src/query/message.rs
  crates/fuel-core/src/query/message/test.rs
  crates/fuel-core/src/schema/message.rs
Labels: no changelog

#2384 Remove ignore RUSTSEC-2024-0336
  .cargo/audit.toml
Labels: no changelog

#2404 Add codeowners for gas price algorithm crate
  .github/CODEOWNERS
Labels: no changelog

#2410 chore(gas_price_service_v0): remove unused trait impl
  crates/services/gas_price_service/src/v0/service.rs
  crates/services/gas_price_service/src/v0/tests.rs
Labels: tech-debt, no changelog

#2409 Update tai64 to fix the wrong time offset
  Cargo.lock
  crates/client/Cargo.toml
  crates/types/Cargo.toml
Labels: no changelog

#2418 Satisfy clippy in `gas-price-analysis`
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/charts.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation/da_cost_per_byte.rs
Labels: no changelog
