Repository FuelLabs/fuel-core, pull requests merged in 2024-09, with the labels that each got.

#2156 Convert gas price analysis tool to CLI
  crates/fuel-gas-price-algorithm/gas-price-analysis/.gitignore
  crates/fuel-gas-price-algorithm/gas-price-analysis/Cargo.toml
  crates/fuel-gas-price-algorithm/gas-price-analysis/gas_prices.png
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/main.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/optimisation.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
Labels: no changelog

#2152 Add label nochangelog on weekly cargo update
  .github/workflows/dependencies.yml
Labels: no changelog

#2168 chore(rocks_db): move ShallowTempDir to benches crate
  benches/benches/vm_set/blockchain.rs
  benches/src/lib.rs
  benches/src/utils.rs
  crates/fuel-core/src/state/rocks_db.rs
Labels: no changelog

#2170 chore(benches): conditional dropping of databases in benchmarks
  benches/src/utils.rs
Labels: tech-debt, no changelog

#2172 chore(shallow_temp_dir): panic if not panicking
  benches/src/utils.rs
Labels: tech-debt, no changelog

#2179 chore: Add initial CODEOWNERS file
  .github/CODEOWNERS
Labels: no changelog

#2173 bug: fix algorithm overflow issues
  Cargo.lock
  bin/fuel-core/chainspec/local-testnet/state_transition_bytecode.wasm
  crates/fuel-gas-price-algorithm/Cargo.toml
  crates/fuel-gas-price-algorithm/gas-price-analysis/Cargo.toml
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/main.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/optimisation.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation/da_cost_per_byte.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/algorithm_v1_tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_da_record_data_tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_l2_block_data_tests.rs
Labels: no changelog

#2201 Fix bug with gas price factor in V1 algorithm
  bin/fuel-core/chainspec/local-testnet/state_transition_bytecode.wasm
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/algorithm_v1_tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_l2_block_data_tests.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater.rs
Labels: no changelog

#2199 Applying several breaking changes to the WASM interface from backlog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/e2e-test-client/Cargo.toml
  bin/e2e-test-client/src/tests/script.rs
  bin/e2e-test-client/tests/integration_tests.rs
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  bin/fuel-core/chainspec/local-testnet/state_transition_bytecode.wasm
  bin/fuel-core/src/cli.rs
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/client/assets/schema.sdl
  crates/client/src/client/schema/chain.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__chain__tests__chain_gql_query_output.snap
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/lib.rs
  crates/fuel-core/src/query/message/test.rs
  crates/fuel-core/src/schema/chain.rs
  crates/fuel-core/src/schema/tx/input.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/executor.rs
  crates/fuel-core/src/service/adapters/producer.rs
  crates/services/consensus_module/poa/src/service_test.rs
  crates/services/executor/Cargo.toml
  crates/services/executor/src/executor.rs
  crates/services/executor/src/ports.rs
  crates/services/upgradable-executor/Cargo.toml
  crates/services/upgradable-executor/src/executor.rs
  crates/services/upgradable-executor/src/instance.rs
  crates/services/upgradable-executor/wasm-executor/Cargo.toml
  crates/services/upgradable-executor/wasm-executor/src/ext.rs
  crates/services/upgradable-executor/wasm-executor/src/main.rs
  crates/services/upgradable-executor/wasm-executor/src/tx_source.rs
  crates/services/upgradable-executor/wasm-executor/src/utils.rs
  crates/types/src/services/block_producer.rs
  crates/types/src/services/executor.rs
  deployment/e2e-client.Dockerfile
  tests/test-helpers/src/builder.rs
  version-compatibility/Cargo.toml
  version-compatibility/forkless-upgrade/Cargo.toml
  version-compatibility/forkless-upgrade/src/backward_compatibility.rs
  version-compatibility/forkless-upgrade/src/forward_compatibility.rs
  version-compatibility/forkless-upgrade/src/lib.rs
  version-compatibility/forkless-upgrade/src/tests_helper.rs
  version-compatibility/placeholder/Cargo.toml
  version-compatibility/placeholder/src/main.rs
Labels: breaking

#2214 fix: use core-test.fuellabs.net for dnsaddr resolution
  crates/services/p2p/src/dnsaddr_resolution.rs
Labels: no changelog

#2215 Removed state transition bytecode from the local testnet
  .gitignore
  bin/fuel-core/chainspec/local-testnet/state_transition_bytecode.wasm
  crates/chain-config/src/config/chain.rs
  tests/tests/local_node.rs
Labels: no changelog

#2222 fix(dnsaddr_resolution): use fqdn separator to prevent suffixing by dns resolvers
  crates/services/p2p/src/dnsaddr_resolution.rs
Labels: no changelog

#2219 Implement worst case scenario for price algorithm v1
  crates/fuel-gas-price-algorithm/src/lib.rs
  crates/fuel-gas-price-algorithm/src/utils.rs
  crates/fuel-gas-price-algorithm/src/v0.rs
  crates/fuel-gas-price-algorithm/src/v0/tests/algorithm_v0_tests.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/algorithm_v1_tests.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater.rs
Labels: no changelog

#2224 chore(gas_price_service): define port for L2 data
  crates/fuel-core/src/service/adapters/gas_price_adapters.rs
  crates/fuel-core/src/service/sub_services/algorithm_updater.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater/fuel_core_storage_adapter.rs
  crates/services/gas_price_service/src/lib.rs
  crates/services/gas_price_service/src/ports.rs
Labels: no changelog

#2229 Use fees to calculate DA reward and avoid issues with Gwei/Wei conversions
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/charts.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_l2_block_data_tests.rs
Labels: no changelog

#2241 Protect against passing `i128::MIN` to `abs()` which causes overflow
  crates/fuel-gas-price-algorithm/src/v1.rs
Labels: no changelog

#2240 Acquire `da_finalization_period` from the command line
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/charts.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/main.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/optimisation.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_l2_block_data_tests.rs
Labels: no changelog

#2242 Executor: test Tx_count limit with incorrect tx source
  crates/fuel-core/src/executor.rs
Labels: no changelog

#2250 Minor updates to docs + a few typos fixed
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/executor.rs
  crates/fuel-core/src/service/adapters/executor.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_da_record_data_tests.rs
  crates/services/consensus_module/poa/src/signer.rs
  docs/developers/debugging.md
Labels: no changelog

#2246 chore(gas_price_service): move algorithm_updater to fuel-core-gas-price-service
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters/gas_price_adapters.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater/algorithm_updater.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater/fuel_core_storage_adapter.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater/fuel_core_storage_adapter/l2_source_tests.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater/fuel_core_storage_adapter/metadata_tests.rs
  crates/services/gas_price_service/src/fuel_gas_price_updater/tests.rs
  crates/services/gas_price_service/src/ports.rs
Labels: no changelog

#2205 Use single heavy input in the `transaction_throughput.rs` benchmarks
  benches/benches/transaction_throughput.rs
  tests/test-helpers/src/builder.rs
Labels: no changelog

#2254 Minor improvements to the compression crate
  crates/compression/Cargo.toml
  crates/compression/src/compress.rs
  crates/compression/src/decompress.rs
  crates/compression/src/eviction_policy.rs
  crates/compression/src/lib.rs
  crates/compression/src/ports.rs
  crates/compression/src/tables.rs
  crates/fuel-core/src/graphql_api/da_compression.rs
  crates/types/src/blockchain/block.rs
Labels: no changelog

#2259 Minimized the number of the tables for metadata and reverse index
  Cargo.lock
  crates/compression/Cargo.toml
  crates/compression/src/compress.rs
  crates/compression/src/decompress.rs
  crates/compression/src/eviction_policy.rs
  crates/compression/src/lib.rs
  crates/compression/src/ports.rs
  crates/compression/src/registry.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/graphql_api/da_compression.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/graphql_api/storage/da_compression.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/metadata_key.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/predicate_code_codec.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/reverse_key.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/script_code_codec.rs
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
  crates/storage/src/lib.rs
  crates/types/src/blockchain/header.rs
Labels: no changelog
