Repository FuelLabs/fuel-core, pull requests merged in 2024-04, with the labels that each got.

#1806 Add PR template
  .github/pull_request_template.md
Labels: documentation, no changelog

#1799 feat: Parallellize snapshot creation
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli.rs
  bin/fuel-core/src/cli/snapshot.rs
  bin/fuel-core/src/main.rs
  crates/chain-config/Cargo.toml
  crates/chain-config/src/config/snapshot_metadata.rs
  crates/chain-config/src/config/state.rs
  crates/chain-config/src/config/state/writer.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/exporter.rs
  crates/fuel-core/src/service/genesis/exporter/filter.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/import_task.rs
  crates/fuel-core/src/service/genesis/importer/off_chain.rs
  crates/fuel-core/src/service/genesis/importer/on_chain.rs
  crates/fuel-core/src/service/genesis/task_manager.rs
  crates/fuel-core/src/service/genesis/workers.rs
  tests/tests/deployment.rs
Labels: enhancement

#1821 feat: (re)genesis graceful shutdown
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/snapshot.rs
  crates/chain-config/src/config/state.rs
  crates/chain-config/src/config/state/parquet.rs
  crates/chain-config/src/config/state/parquet/decode.rs
  crates/chain-config/src/config/state/reader.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/p2p_test_helpers.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/exporter.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/import_task.rs
  crates/fuel-core/src/service/genesis/importer/progress.rs
  crates/fuel-core/src/service/genesis/task_manager.rs
  crates/services/src/state.rs
  tests/tests/contract.rs
  tests/tests/messages.rs
Labels: enhancement

#1822 Use `fuel-vm 0.49.0` with new transactions types
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  benches/benches/state.rs
  benches/benches/vm_set/blockchain.rs
  bin/e2e-test-client/src/tests/test_data/large_state/chain_config.json
  bin/fuel-core/chainspec/dev-testnet/chain_config.json
  bin/fuel-core/chainspec/testnet/chain_config.json
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_configurable_block_height.snap
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_configurable_block_height.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_contract_with_balances.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_contract_with_state.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_contract_with_tx_pointer.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_contract_with_utxo_id.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_local_testnet_config.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_simple_coin_state.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_simple_contract.snap
  crates/chain-config/src/snapshots/fuel_core_chain_config__config__tests__snapshot_simple_message_state.snap
  crates/client/assets/schema.sdl
  crates/client/src/client/schema/chain.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__chain__tests__chain_gql_query_output.snap
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__tx__tests__transparent_transaction_by_id_query_gql_output.snap
  crates/client/src/client/schema/tx/transparent_tx.rs
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/fuel-core/src/schema/chain.rs
  crates/fuel-core/src/schema/dap.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/schema/tx/types.rs
  crates/fuel-core/src/schema/tx/upgrade_purpose.rs
  crates/fuel-core/src/service/genesis.rs
  crates/services/executor/src/executor.rs
  crates/services/executor/src/ports.rs
  crates/services/txpool/src/txpool.rs
  crates/services/upgradable-executor/build.rs
  crates/services/upgradable-executor/src/executor.rs
  crates/storage/src/column.rs
  crates/storage/src/structured_storage/upgrades.rs
  crates/storage/src/tables.rs
  crates/storage/src/vm_storage.rs
  crates/types/src/lib.rs
  crates/types/src/services/txpool.rs
  tests/Cargo.toml
  tests/test-helpers/src/builder.rs
  tests/tests/tx.rs
  tests/tests/tx/predicates.rs
  tests/tests/tx/txpool.rs
  tests/tests/tx/upgrade.rs
Labels: breaking

#1811 Store old blocks and txs after regenesis
  CHANGELOG.md
  Cargo.lock
  bin/fuel-core/chainspec/dev-testnet/state_transition_bytecode.wasm
  bin/fuel-core/chainspec/testnet/state_transition_bytecode.wasm
  bin/fuel-core/src/cli.rs
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/lib.rs
  bin/fuel-core/src/main.rs
  crates/chain-config/src/config/randomize.rs
  crates/chain-config/src/config/state.rs
  crates/fuel-core/src/graphql_api/database.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/graphql_api/storage/old.rs
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/fuel-core/src/p2p_test_helpers.rs
  crates/fuel-core/src/query/tx.rs
  crates/fuel-core/src/schema/block.rs
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
  crates/fuel-core/src/service/adapters/graphql_api/on_chain.rs
  crates/fuel-core/src/service/genesis/exporter.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/import_task.rs
  crates/fuel-core/src/service/genesis/importer/off_chain.rs
  crates/fuel-core/src/service/genesis/importer/on_chain.rs
  crates/fuel-core/src/service/genesis/importer/progress.rs
  tests/Cargo.toml
  tests/tests/lib.rs
  tests/tests/poa.rs
  tests/tests/regenesis.rs
Labels: graphql-api, regenesis

#1856 fix: Use `Enum` for `ConsensusParametersVersion` and related types
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client/schema/chain.rs
  crates/client/src/client/schema/primitives.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__chain__tests__chain_gql_query_output.snap
  crates/fuel-core/src/schema/chain.rs
Labels: breaking

#1832 feat: snapshot generation graceful shutdown
  CHANGELOG.md
  Cargo.lock
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli.rs
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/snapshot.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/exporter.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/import_task.rs
  crates/fuel-core/src/service/genesis/importer/progress.rs
  crates/fuel-core/src/service/genesis/progress.rs
  crates/fuel-core/src/service/genesis/task_manager.rs
Labels: enhancement

#1861 fix: Use Enum for GQL versions (0.24.3)
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client/schema/chain.rs
  crates/client/src/client/schema/primitives.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__chain__tests__chain_gql_query_output.snap
  crates/fuel-core/src/schema/chain.rs
Labels: breaking

#1860 regenesis: migrate FuelBlockIdsToHeights
  CHANGELOG.md
  benches/benches/block_target_gas.rs
  benches/benches/vm.rs
  benches/benches/vm_set/blockchain.rs
  benches/src/lib.rs
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/genesis_progress.rs
  crates/fuel-core/src/database/metadata.rs
  crates/fuel-core/src/database/storage.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/exporter.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/import_task.rs
  crates/fuel-core/src/service/genesis/importer/off_chain.rs
  crates/fuel-core/src/service/genesis/importer/on_chain.rs
  crates/fuel-core/src/state/in_memory/memory_store.rs
  crates/fuel-core/src/state/rocks_db.rs
  crates/services/src/lib.rs
  crates/services/src/service.rs
  crates/services/src/sync.rs
Labels: fuel-database, regenesis

#1866 test: restart with relayer data
  CHANGELOG.md
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/service/adapters/consensus_module.rs
  crates/fuel-core/src/service/adapters/producer.rs
  crates/fuel-core/src/service/adapters/relayer.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/relayer/src/mock_db.rs
  crates/services/relayer/src/ports.rs
  crates/services/relayer/src/ports/tests.rs
  crates/services/relayer/src/service.rs
  crates/services/relayer/src/service/get_logs/test.rs
  crates/services/relayer/src/service/test.rs
  crates/services/relayer/src/storage.rs
  crates/services/relayer/tests/integration.rs
  tests/tests/relayer.rs
Labels: breaking
