Repository FuelLabs/fuel-core, pull requests merged in 2025-03, with the labels that each got.

#2787 fix(ci): typos according to new version of spellcheck ci
  .typos.toml
Labels: no changelog

#2798 fix: Mark (temporarily) dead code with `#[allow(dead_code)]`
  crates/fuel-core/src/service/adapters/consensus_module/poa/pre_confirmation_signature/tx_receiver.rs
  crates/services/consensus_module/poa/src/pre_confirmation_signature_service.rs
  crates/services/consensus_module/poa/src/pre_confirmation_signature_service/parent_signature.rs
Labels: no changelog

#2702 Use `remove_recovery_id()` from `Signature`
  crates/services/shared-sequencer/src/lib.rs
Labels: no changelog

#2616 Use `Display` from `Receipt` enum
  crates/fuel-core/src/graphql_api/indexation/asset_metadata.rs
Labels: no changelog

#2804 Fix version of symbolic common
  version-compatibility/forkless-upgrade/Cargo.toml
  version-compatibility/forkless-upgrade/src/lib.rs
Labels: no changelog

#2810 Bump versions 0.41.8
  Cargo.lock
  Cargo.toml
  README.md
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/blockchain/header.rs
Labels: no changelog

#2812 Revert fix version of symbolic-common dependency
  version-compatibility/forkless-upgrade/Cargo.toml
  version-compatibility/forkless-upgrade/src/lib.rs
Labels: no changelog

#2816 Resolve RUSTSEC-2025-0006
  .cargo/audit.toml
  Cargo.lock
Labels: no changelog

#2830 fix(sub_services): enable block production only after all other services have been started
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/block_production_trigger.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/consensus_module/poa/src/ports.rs
  crates/services/consensus_module/poa/src/service.rs
  crates/services/consensus_module/poa/src/service_test.rs
Labels: no changelog

#2829 fix(relayer): ensure local state is updated after logs downloaded
  .cargo/audit.toml
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/block_production_trigger.rs
  crates/fuel-core/src/service/adapters/consensus_module.rs
  crates/fuel-core/src/service/adapters/producer.rs
  crates/fuel-core/src/service/adapters/relayer.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/consensus_module/poa/src/ports.rs
  crates/services/consensus_module/poa/src/service.rs
  crates/services/consensus_module/poa/src/service_test.rs
  crates/services/relayer/src/ports.rs
  crates/services/relayer/src/service.rs
  crates/services/relayer/src/service/run.rs
  crates/services/relayer/src/service/run/test.rs
  crates/services/relayer/src/service/state.rs
  crates/services/relayer/src/service/state/state_builder.rs
  crates/services/relayer/src/service/state/test.rs
  crates/services/relayer/src/service/test.rs
  crates/services/relayer/tests/integration.rs
  crates/services/src/service.rs
Labels: no changelog

#2831 chore(v0.41.9): bump versions, release changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/blockchain/header.rs
Labels: no changelog

#2788 fault_proving(compression_service): initial scaffold for dedicated compression service
  .changes/added/2788.md
  .github/CODEOWNERS
  Cargo.lock
  Cargo.toml
  crates/services/compression/Cargo.toml
  crates/services/compression/src/config.rs
  crates/services/compression/src/errors.rs
  crates/services/compression/src/lib.rs
  crates/services/compression/src/ports.rs
  crates/services/compression/src/ports/block_source.rs
  crates/services/compression/src/ports/compression_storage.rs
  crates/services/compression/src/ports/configuration.rs
  crates/services/compression/src/service.rs
  crates/services/compression/src/storage.rs
Labels: fault-proving

#2828 Applied part of follow-up changes to the `TxStatusManager`
  Cargo.lock
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/run/tx_status_manager.rs
  crates/fuel-core/src/executor.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/query/subscriptions.rs
  crates/fuel-core/src/query/subscriptions/test.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/schema/tx/types.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/consensus_module/poa.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/adapters/tx_status_manager.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/service/query.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/tx_status_manager/Cargo.toml
  crates/services/tx_status_manager/src/config.rs
  crates/services/tx_status_manager/src/lib.rs
  crates/services/tx_status_manager/src/manager.rs
  crates/services/tx_status_manager/src/service.rs
  crates/services/tx_status_manager/src/tests/tests_e2e.rs
  crates/services/tx_status_manager/src/tests/tests_sending.rs
  crates/services/tx_status_manager/src/tests/tests_update_stream_state.rs
  crates/services/tx_status_manager/src/tests/universe.rs
  crates/services/tx_status_manager/src/tests/utils.rs
  crates/services/tx_status_manager/src/tx_status_stream.rs
  crates/services/tx_status_manager/src/update_sender.rs
  crates/services/txpool_v2/src/service.rs
  crates/services/txpool_v2/src/tests/tests_pending_pool.rs
  crates/services/txpool_v2/src/tests/tests_service.rs
  crates/types/src/services/txpool.rs
Labels: no changelog

#2867 fix(versions): port bump to v0.41.9
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/blockchain/header.rs
Labels: no changelog

#2868 Add metrics to `TxStatusManager` service
  Cargo.lock
  bin/fuel-core/src/cli/run.rs
  crates/metrics/src/config.rs
  crates/metrics/src/lib.rs
  crates/metrics/src/tx_status_manager_metrics.rs
  crates/services/tx_status_manager/Cargo.toml
  crates/services/tx_status_manager/src/config.rs
  crates/services/tx_status_manager/src/manager.rs
  crates/services/tx_status_manager/src/service.rs
  crates/services/tx_status_manager/src/tests/universe.rs
Labels: no changelog

#2819 fault_proving(compression): add table definitions reusing new storage trait impls
  Cargo.lock
  crates/services/compression/Cargo.toml
  crates/services/compression/src/lib.rs
  crates/services/compression/src/storage.rs
  crates/services/compression/src/storage/address.rs
  crates/services/compression/src/storage/asset_id.rs
  crates/services/compression/src/storage/column.rs
  crates/services/compression/src/storage/compressed_blocks.rs
  crates/services/compression/src/storage/contract_id.rs
  crates/services/compression/src/storage/evictor_cache.rs
  crates/services/compression/src/storage/predicate_code.rs
  crates/services/compression/src/storage/registry_index.rs
  crates/services/compression/src/storage/script_code.rs
Labels: no changelog

#2844 fault_proving(compression): implement compression in compression service
  .changes/added/2844.md
  Cargo.lock
  crates/services/compression/Cargo.toml
  crates/services/compression/src/config.rs
  crates/services/compression/src/errors.rs
  crates/services/compression/src/lib.rs
  crates/services/compression/src/ports/block_source.rs
  crates/services/compression/src/ports/compression_storage.rs
  crates/services/compression/src/service.rs
  crates/services/compression/src/storage.rs
  crates/services/compression/src/storage/address.rs
  crates/services/compression/src/storage/asset_id.rs
  crates/services/compression/src/storage/column.rs
  crates/services/compression/src/storage/compressed_blocks.rs
  crates/services/compression/src/storage/contract_id.rs
  crates/services/compression/src/storage/evictor_cache.rs
  crates/services/compression/src/storage/predicate_code.rs
  crates/services/compression/src/storage/registry_index.rs
  crates/services/compression/src/storage/script_code.rs
  crates/services/compression/src/storage/timestamps.rs
  crates/services/compression/src/temporal_registry.rs
Labels: fault-proving

#2881 fix(ci): e2e-client-dockerfile build
  deployment/e2e-client.Dockerfile
Labels: no changelog

#2884 fix(ci): check-changelog should run only if its a PR
  .github/workflows/ci.yml
Labels: no changelog

#2871 Rework `TxStatusManager` tests
  crates/services/tx_status_manager/Cargo.toml
  crates/services/tx_status_manager/src/lib.rs
  crates/services/tx_status_manager/src/manager.rs
  crates/services/tx_status_manager/src/service.rs
  crates/services/tx_status_manager/src/tests/universe.rs
Labels: no changelog

#2875 fix(storage): custom impl of EnumCount for MerkleizedColumn
  crates/storage/src/merkle/column.rs
Labels: no changelog

#2891 fix(version-compatibility): pin async-graphql to 7.0.15
  version-compatibility/forkless-upgrade/Cargo.toml
  version-compatibility/forkless-upgrade/src/lib.rs
Labels: no changelog

#2893 Fix proptest for tx status manager
  crates/services/tx_status_manager/proptest-regressions/service.txt
  crates/services/tx_status_manager/src/service.rs
Labels: no changelog

#2859 fault_proving(compression): glue code for integ into fuel-core
  .changes/changed/2859.md
  .changes/removed/2859.md
  Cargo.lock
  Cargo.toml
  benches/benches/block_target_gas.rs
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/database_description.rs
  crates/fuel-core/src/database/database_description/compression.rs
  crates/fuel-core/src/graphql_api.rs
  crates/fuel-core/src/graphql_api/api_service.rs
  crates/fuel-core/src/graphql_api/da_compression.rs
  crates/fuel-core/src/graphql_api/database.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/graphql_api/storage/da_compression.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/evictor_cache.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/predicate_code_codec.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/reverse_key.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/script_code_codec.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/timestamps.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/address.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/asset_id.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/contract_id.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/evictor_cache.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/predicate_code.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/registry_index.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/script_code.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/timestamps.rs
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/fuel-core/src/graphql_api/worker_service/tests.rs
  crates/fuel-core/src/query.rs
  crates/fuel-core/src/query/da_compressed.rs
  crates/fuel-core/src/schema/da_compressed.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/compression_adapters.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/compression/src/errors.rs
  crates/services/compression/src/lib.rs
  crates/services/compression/src/ports/block_source.rs
  crates/services/compression/src/service.rs
  crates/services/compression/src/sync_state.rs
  tests/Cargo.toml
  tests/tests/da_compression.rs
Labels: fault-proving, xxx

#2895 fix(compression_service): post merge reviews
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/database/database_description/compression.rs
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/service/adapters/compression_adapters.rs
  crates/fuel-core/src/state/in_memory/memory_store.rs
  crates/services/compression/src/ports/block_source.rs
  crates/services/compression/src/service.rs
  crates/storage/src/merkle/column.rs
Labels: no changelog

#2909 chore(compression): include registry root in compressed block header
  .changes/breaking/2909.md
  .github/workflows/ci.yml
  crates/compression/src/compress.rs
  crates/compression/src/compressed_block_payload/v1.rs
  crates/compression/src/decompress.rs
  crates/compression/src/lib.rs
  crates/compression/src/ports.rs
  crates/fuel-core/Cargo.toml
  crates/services/compression/Cargo.toml
  crates/services/compression/src/errors.rs
  crates/services/compression/src/temporal_registry.rs
  tests/Cargo.toml
Labels: breaking
