Repository FuelLabs/fuel-core, pull requests merged in 2025-04, with the labels that each got.

#2911 Improve TxStatusManager tests coverage
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/services/tx_status_manager/src/service.rs
  crates/services/tx_status_manager/src/tests/mocks.rs
  crates/services/tx_status_manager/src/tests/mod.rs
  crates/services/tx_status_manager/src/tests/tests_service.rs
  crates/services/tx_status_manager/src/tests/universe.rs
  crates/services/txpool_v2/src/tests/mod.rs
  crates/services/txpool_v2/src/tests/tx_status_manager_integration.rs
  crates/services/txpool_v2/src/tests/universe.rs
Labels: no changelog

#2915 ci(benchmarks): run nightly benchmark and create PR
  .github/workflows/nightly-benchmark.yml
Labels: no changelog

#2922 fix(ci): nightly benchmark
  .github/workflows/nightly-benchmark.yml
Labels: no changelog

#2926 fix(ci): explicitly push before creating PR
  .github/workflows/nightly-benchmark.yml
Labels: no changelog

#2923 fix(compression): improve robustness on startup and shutdown
  crates/fuel-core/src/service/adapters/compression_adapters.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/adapters/import_result_provider.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/compression/src/ports.rs
  crates/services/compression/src/ports/block_source.rs
  crates/services/compression/src/ports/canonical_height.rs
  crates/services/compression/src/ports/compression_storage.rs
  crates/services/compression/src/ports/configuration.rs
  crates/services/compression/src/service.rs
Labels: bug, no changelog, fault-proving

#2920 chore(compression): metrics for compression service
  Cargo.lock
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/src/service/adapters/compression_adapters.rs
  crates/fuel-core/src/service/config.rs
  crates/metrics/src/compression_metrics.rs
  crates/metrics/src/config.rs
  crates/metrics/src/lib.rs
  crates/services/compression/Cargo.toml
  crates/services/compression/src/config.rs
  crates/services/compression/src/errors.rs
  crates/services/compression/src/lib.rs
  crates/services/compression/src/metrics.rs
  crates/services/compression/src/ports/compression_storage.rs
  crates/services/compression/src/service.rs
  tests/tests/da_compression.rs
Labels: no changelog

#2901 Dry run execution tracing
  .changes/added/2901.md
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema/storage_read_replay.rs
  crates/client/src/client/schema/tx.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/schema/tx/assemble_tx.rs
  crates/fuel-core/src/schema/tx/types.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/adapters/producer.rs
  crates/services/executor/src/executor.rs
  crates/services/producer/src/block_producer.rs
  crates/services/producer/src/block_producer/tests.rs
  crates/services/producer/src/mocks.rs
  crates/services/producer/src/ports.rs
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/services.rs
  crates/types/src/services/executor.rs
  tests/tests/storage_read_replay.rs
Labels: fuel-block-executor, graphql-api

#2937 chore(1.85): 1.85.0 readiness
  Cargo.lock
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
Labels: no changelog

#2939 Release v0.43.0
  .changes/added/2848.md
  .changes/added/2882.md
  .changes/added/2885.md
  .changes/added/2901.md
  .changes/added/2912.md
  .changes/added/2914.md
  .changes/breaking/2882.md
  .changes/breaking/2900.md
  .changes/breaking/2909.md
  .changes/breaking/2931.md
  .changes/changed/2859.md
  .changes/changed/2914.md
  .changes/changed/2925.md
  .changes/fixed/2918.md
  .changes/fixed/2935.md
  .changes/removed/2859.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/blockchain/header.rs
Labels: no changelog, release, pr release

#2941 Fix publishing by using `async-graphql 7.0.15`
  Cargo.toml
Labels: no changelog

#2945 Try to fix flakiness in p2p tests
  crates/fuel-core/src/service/query.rs
Labels: no changelog

#2954 chore(compression): make registry mod public
  .changes/added/2954.md
  crates/compression/src/lib.rs
Labels: no changelog

#2964 chore(tx|gas_price): add test to ensure heap memory is cleared, add gm opcode integ test
  Cargo.lock
  Cargo.toml
  tests/tests/gas_price.rs
  tests/tests/tx.rs
  tests/tests/tx/vm_memory.rs
Labels: no changelog

#2965 chore(v0.41.10): bump versions, release changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/blockchain/header.rs
Labels: no changelog

#2936 Add benches for all opcodes
  benches/benches/vm_set/flow.rs
  bin/fuel-core/chainspec/local-testnet/README.md
Labels: no changelog

#2978 fix(compression_service): prevent syncing from genesis if compression db is empty
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/run/p2p.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters/compression_adapters.rs
  crates/fuel-core/src/service/config.rs
  crates/services/compression/src/config.rs
  crates/services/compression/src/ports/block_source.rs
  crates/services/compression/src/service.rs
  crates/services/compression/src/sync_state.rs
  crates/services/src/service.rs
  crates/services/src/state.rs
  tests/tests/da_compression.rs
Labels: no changelog

#2980 chore(v0.43.2): bump versions
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/blockchain/header.rs
Labels: no changelog
