Repository FuelLabs/fuel-core, pull requests merged in 2025-01, with the labels that each got.

#2456 Update bhsh bench
  benches/benches/vm_set/blockchain.rs
  benches/src/default_gas_costs.rs
  bin/e2e-test-client/src/tests/test_data/large_state/chain_config.json
  bin/fuel-core/chainspec/local-testnet/chain_config.json
Labels: no changelog

#2505 Integration test for balances and (non)retryable messages
  tests/tests/balances.rs
  tests/tests/relayer.rs
Labels: no changelog

#2502 Add document for launching Ignition node from source and Local network from source
  README.md
Labels: no changelog

#2526 Make the rocksdb cache optional in config and add policy for column opening
  CHANGELOG.md
  benches/Cargo.toml
  benches/benches/block_target_gas.rs
  benches/benches/state.rs
  benches/benches/transaction_throughput.rs
  benches/benches/vm_set/blockchain.rs
  benches/src/db_lookup_times_utils/utils.rs
  bin/fuel-core/src/cli/rollback.rs
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/snapshot.rs
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/graphql_api/indexation.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/state/historical_rocksdb.rs
  crates/fuel-core/src/state/rocks_db.rs
  tests/test-helpers/src/builder.rs
  tests/tests/aws_kms.rs
  tests/tests/health.rs
  tests/tests/relayer.rs
Labels: breaking

#2534 chore(codeowners): gas price service codeowners
  .github/CODEOWNERS
Labels: no changelog

#2512 Fix for DA L2 sync race condition
  crates/services/gas_price_service/src/common/utils.rs
  crates/services/gas_price_service/src/v1/da_source_service.rs
  crates/services/gas_price_service/src/v1/da_source_service/block_committer_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/dummy_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/service.rs
  crates/services/gas_price_service/src/v1/service.rs
  crates/services/gas_price_service/src/v1/tests.rs
  crates/services/gas_price_service/src/v1/uninitialized_task.rs
  crates/services/src/service.rs
  tests/tests/gas_price.rs
Labels: no changelog

#2540 Read simulation data from file
  crates/services/gas_price_service/simulation/Cargo.toml
  crates/services/gas_price_service/simulation/src/data_sources.rs
  crates/services/gas_price_service/simulation/src/main.rs
  crates/services/gas_price_service/simulation/src/service.rs
Labels: no changelog

#2533 Gas price simulation data retriever
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/.gitignore
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/Cargo.toml
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/README.md
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/build.rs
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/src/client_ext.rs
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/src/layer1.rs
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/src/layer2.rs
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/src/main.rs
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/src/summary.rs
  crates/fuel-gas-price-algorithm/gas-price-data-fetcher/src/types.rs
  crates/fuel-gas-price-algorithm/gas-price-data-reader/.gitignore
  crates/fuel-gas-price-algorithm/gas-price-data-reader/Cargo.toml
  crates/fuel-gas-price-algorithm/gas-price-data-reader/src/main.rs
Labels: no changelog

#2541 feat(gas_price_service_v1): include `max_da_gas_price` to control volatility
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/src/service/adapters/gas_price_adapters.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_da_record_data_tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_l2_block_data_tests.rs
  crates/services/gas_price_service/src/ports.rs
  crates/services/gas_price_service/src/v1/metadata.rs
  crates/services/gas_price_service/src/v1/service.rs
  crates/services/gas_price_service/src/v1/tests.rs
  tests/tests/gas_price.rs
Labels: no changelog

#2447 Use expiration policy
  CHANGELOG.md
  Cargo.lock
  crates/services/executor/src/executor.rs
  crates/services/executor/src/ports.rs
  crates/services/p2p/src/service.rs
  crates/services/txpool_v2/src/service.rs
  crates/services/txpool_v2/src/service/pruner.rs
  crates/services/txpool_v2/src/tests/mocks.rs
  crates/services/txpool_v2/src/tests/tests_service.rs
  crates/services/txpool_v2/src/tests/universe.rs
  crates/types/src/services/executor.rs
  crates/types/src/services/txpool.rs
Labels: release

#2515 Fixed TPS benchmark to work with latest changes
  Cargo.toml
  benches/benches/transaction_throughput.rs
  crates/fuel-core/Cargo.toml
  crates/services/executor/Cargo.toml
  crates/services/executor/src/executor.rs
  crates/services/upgradable-executor/Cargo.toml
  tests/Cargo.toml
  tests/test-helpers/src/builder.rs
Labels: no changelog, release

#2529 Use own codec for `CoinsToSpendIndexKey`
  crates/fuel-core/src/coins_query.rs
  crates/fuel-core/src/graphql_api/indexation/coins_to_spend.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/storage/coins.rs
  crates/fuel-core/src/graphql_api/storage/coins/codecs.rs
  crates/fuel-core/src/schema/coins.rs
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
Labels: no changelog, release

#2463 Use indexation cache to satisfy "coins to spend" queries
  CHANGELOG.md
  crates/chain-config/src/config/chain.rs
  crates/client/src/client/schema/coins.rs
  crates/client/src/client/types/balance.rs
  crates/fuel-core/src/coins_query.rs
  crates/fuel-core/src/database/database_description.rs
  crates/fuel-core/src/graphql_api.rs
  crates/fuel-core/src/graphql_api/database.rs
  crates/fuel-core/src/graphql_api/indexation.rs
  crates/fuel-core/src/graphql_api/indexation/balances.rs
  crates/fuel-core/src/graphql_api/indexation/coins_to_spend.rs
  crates/fuel-core/src/graphql_api/indexation/error.rs
  crates/fuel-core/src/graphql_api/indexation/test_utils.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/graphql_api/storage/coins.rs
  crates/fuel-core/src/graphql_api/storage/coins/codecs.rs
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/fuel-core/src/graphql_api/worker_service/tests.rs
  crates/fuel-core/src/query/balance.rs
  crates/fuel-core/src/schema/coins.rs
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/off_chain.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/metrics/src/config.rs
  crates/storage/src/codec.rs
  tests/tests/balances.rs
  tests/tests/coins.rs
  tests/tests/relayer.rs
Labels: release

#2524 feat(txpool|p2p): use seqlock instead of small copy-able RwLocks
  CHANGELOG.md
  crates/services/p2p/src/config.rs
  crates/services/p2p/src/config/connection_tracker.rs
  crates/services/p2p/src/p2p_service.rs
  crates/services/p2p/src/peer_manager.rs
  crates/services/src/lib.rs
  crates/services/src/seqlock.rs
  crates/services/txpool_v2/src/service.rs
Labels: release

#2445 Create new index for tracking Asset metadata
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema.rs
  crates/client/src/client/schema/assets.rs
  crates/client/src/client/schema/primitives.rs
  crates/client/src/client/types.rs
  crates/client/src/client/types/asset.rs
  crates/fuel-core/src/database/database_description.rs
  crates/fuel-core/src/graphql_api/database.rs
  crates/fuel-core/src/graphql_api/indexation.rs
  crates/fuel-core/src/graphql_api/indexation/asset_metadata.rs
  crates/fuel-core/src/graphql_api/indexation/error.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/graphql_api/storage/assets.rs
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/fuel-core/src/graphql_api/worker_service/tests.rs
  crates/fuel-core/src/query.rs
  crates/fuel-core/src/query/assets.rs
  crates/fuel-core/src/schema.rs
  crates/fuel-core/src/schema/assets.rs
  crates/fuel-core/src/schema/scalars.rs
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
  tests/tests/assets.rs
  tests/tests/lib.rs
Labels: release

#2535 feat(rocksdb): remove getters for internal rocksdb handles, expose `backup` instead
  CHANGELOG.md
  crates/database/Cargo.toml
  crates/database/src/lib.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/state/historical_rocksdb.rs
  crates/fuel-core/src/state/rocks_db.rs
  tests/Cargo.toml
  tests/tests/state_rewind.rs
Labels: release

#2469 Integrate with V1 algo for tests
  .gitignore
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/e2e-test-client/tests/integration_tests.rs
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli/run.rs
  ci_checks.sh
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters/fuel_gas_price_provider.rs
  crates/fuel-core/src/service/adapters/gas_price_adapters.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/charts.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/main.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation/da_cost_per_byte.rs
  crates/fuel-gas-price-algorithm/src/v1.rs
  crates/fuel-gas-price-algorithm/src/v1/tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_da_record_data_tests.rs
  crates/fuel-gas-price-algorithm/src/v1/tests/update_l2_block_data_tests.rs
  crates/services/gas_price_service/Cargo.toml
  crates/services/gas_price_service/src/common/fuel_core_storage_adapter.rs
  crates/services/gas_price_service/src/common/fuel_core_storage_adapter/storage.rs
  crates/services/gas_price_service/src/common/updater_metadata.rs
  crates/services/gas_price_service/src/common/utils.rs
  crates/services/gas_price_service/src/ports.rs
  crates/services/gas_price_service/src/v0/uninitialized_task.rs
  crates/services/gas_price_service/src/v1/algorithm.rs
  crates/services/gas_price_service/src/v1/da_source_service.rs
  crates/services/gas_price_service/src/v1/da_source_service/block_committer_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/dummy_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/service.rs
  crates/services/gas_price_service/src/v1/metadata.rs
  crates/services/gas_price_service/src/v1/service.rs
  crates/services/gas_price_service/src/v1/tests.rs
  crates/services/gas_price_service/src/v1/uninitialized_task.rs
  crates/services/gas_price_service/src/v1/uninitialized_task/fuel_storage_unrecorded_blocks.rs
  crates/services/relayer/Cargo.toml
  crates/services/src/service.rs
  tests/Cargo.toml
  tests/test-helpers/src/builder.rs
  tests/test-helpers/src/fuel_core_driver.rs
  tests/tests/chain.rs
  tests/tests/gas_price.rs
  tests/tests/regenesis.rs
  version-compatibility/forkless-upgrade/Cargo.toml
  version-compatibility/forkless-upgrade/src/gas_price_algo_compatibility.rs
  version-compatibility/forkless-upgrade/src/genesis.rs
  version-compatibility/forkless-upgrade/src/lib.rs
  version-compatibility/forkless-upgrade/src/tests_helper.rs
Labels: release

#2523 chore(gas_price_service_v1): strictly ensure last_recorded_height is set, to avoid initial poll of da source
  crates/services/gas_price_service/src/v1/da_source_service.rs
  crates/services/gas_price_service/src/v1/da_source_service/block_committer_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/dummy_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/service.rs
  crates/services/gas_price_service/src/v1/service.rs
  crates/services/gas_price_service/src/v1/tests.rs
  crates/services/gas_price_service/src/v1/uninitialized_task.rs
  tests/tests/gas_price.rs
Labels: no changelog, release

#2546 Lock-free `latest_l2_height` in gas price service
  crates/services/gas_price_service/src/v1/da_source_service.rs
  crates/services/gas_price_service/src/v1/da_source_service/service.rs
  crates/services/gas_price_service/src/v1/service.rs
  crates/services/gas_price_service/src/v1/tests.rs
  crates/services/gas_price_service/src/v1/uninitialized_task.rs
Labels: no changelog, release

#2556 chore(gas_price_service_v1): strictly ensure last_recorded_height is set, to avoid initial poll of da source
  CHANGELOG.md
  crates/services/gas_price_service/src/v1/da_source_service.rs
  crates/services/gas_price_service/src/v1/da_source_service/block_committer_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/dummy_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/service.rs
  crates/services/gas_price_service/src/v1/service.rs
  crates/services/gas_price_service/src/v1/tests.rs
  crates/services/gas_price_service/src/v1/uninitialized_task.rs
  tests/tests/gas_price.rs
Labels: release

#2547 Replace old Graphql Gas Price adapter with new latest gas price struct
  CHANGELOG.md
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/src/p2p_test_helpers.rs
  crates/fuel-core/src/service/adapters/fuel_gas_price_provider.rs
  crates/fuel-core/src/service/adapters/fuel_gas_price_provider/tests.rs
  crates/fuel-core/src/service/adapters/fuel_gas_price_provider/tests/graph_ql_gas_price_estimate_tests.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/gas_price_service/src/v1/uninitialized_task.rs
  tests/tests/gas_price.rs
  tests/tests/poa.rs
Labels: release

#2550 Add current pool gas to the node info endpoint
  CHANGELOG.md
  crates/client/assets/schema.sdl
  crates/client/src/client/schema/node_info.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__node_info__tests__node_info_query_gql_output.snap
  crates/client/src/client/types/node_info.rs
  crates/fuel-core/src/graphql_api.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/schema/node_info.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/txpool_v2/src/lib.rs
  crates/services/txpool_v2/src/pool.rs
  crates/services/txpool_v2/src/service.rs
  crates/services/txpool_v2/src/shared_state.rs
  crates/services/txpool_v2/src/tests/universe.rs
  tests/tests/node_info.rs
Labels: release

#2490 Pagination queries for `balances` endpoint
  CHANGELOG.md
  crates/fuel-core/src/graphql_api.rs
  crates/fuel-core/src/graphql_api/api_service.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/worker_service.rs
  crates/fuel-core/src/query/balance.rs
  crates/fuel-core/src/schema/balance.rs
  crates/fuel-core/src/service/adapters/graphql_api/off_chain.rs
  crates/services/gas_price_service/src/common/utils.rs
  crates/services/src/service.rs
  tests/tests/balances.rs
  tests/tests/dos.rs
Labels: breaking, release

#2563 Add test expiration policy in executor
  crates/fuel-core/src/executor.rs
Labels: no changelog

#2557 Code owners for the indexation
  .github/CODEOWNERS
Labels: no changelog

#2551 fault_proving(compression): include block_id in da compressed block headers
  CHANGELOG.md
  Cargo.lock
  bin/fuel-core/Cargo.toml
  crates/compression/Cargo.toml
  crates/compression/src/compress.rs
  crates/compression/src/compressed_block_payload/mod.rs
  crates/compression/src/compressed_block_payload/v0.rs
  crates/compression/src/compressed_block_payload/v1.rs
  crates/compression/src/decompress.rs
  crates/compression/src/lib.rs
  crates/fuel-core/Cargo.toml
Labels: fault-proving

#2570 chore: Add myself and Andrea as codeowner for graphql API + related crates
  .github/CODEOWNERS
  benches/README.md
Labels: no changelog

#2566 fix(integration_tests): remove flake from produce_block__l1_committed_block_affects_gas_price
  tests/tests/gas_price.rs
Labels: no changelog

#2608 Fix version compatibility error
  version-compatibility/forkless-upgrade/Cargo.toml
  version-compatibility/forkless-upgrade/src/lib.rs
Labels: no changelog

#2604 Propose new idea to store the indexation info
  crates/fuel-core/src/schema/node_info.rs
Labels: no changelog

#2577 Update async processor tests
  crates/services/src/async_processor.rs
Labels: no changelog

#2593 fix(da_compression): invalid decompression of utxo id and CoinConfig fix
  CHANGELOG.md
  crates/chain-config/src/config/coin.rs
  crates/chain-config/src/config/state.rs
  crates/compression/src/decompress.rs
  crates/fuel-core/src/graphql_api/da_compression.rs
  crates/fuel-core/src/p2p_test_helpers.rs
  tests/tests/balances.rs
  tests/tests/coin.rs
  tests/tests/coins.rs
  tests/tests/da_compression.rs
Labels: bug

#2594 Check that fuel-core lib builds correctly without default features
  .github/workflows/ci.yml
  ci_checks.sh
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/database.rs
Labels: no changelog

#2623 Pin netlink-proto version
  Cargo.lock
  crates/services/p2p/Cargo.toml
Labels: no changelog

#2624 Release v0.41.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/services/upgradable-executor/src/executor.rs
Labels: release

#2626 fix(rocksdb): import when rocksdb is enabled within local_node_with_reader fn
  crates/fuel-core/src/service/config.rs
Labels: no changelog

#2631 Add generation of docker images on release/master push
  .github/workflows/docker-images.yml
Labels: no changelog

#2634 chore(async_trait): reduce usage of async_trait for small types again
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/schema/gas_price.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/adapters/sync.rs
  crates/services/gas_price_service/src/common/gas_price_algorithm.rs
  crates/services/gas_price_service/src/v0/service.rs
  crates/services/gas_price_service/src/v1/service.rs
  crates/services/sync/src/import/test_helpers/pressure_block_importer.rs
  crates/services/sync/src/import/test_helpers/pressure_consensus.rs
  crates/services/sync/src/import/tests.rs
  crates/services/sync/src/ports.rs
  crates/services/sync/src/service/tests.rs
Labels: no changelog

#2636 chore(gas_price_service): minor refactors to make the code more readable
  crates/services/gas_price_service/src/common/fuel_core_storage_adapter.rs
  crates/services/gas_price_service/src/common/updater_metadata.rs
  crates/services/gas_price_service/src/v0/service.rs
  crates/services/gas_price_service/src/v0/uninitialized_task.rs
  crates/services/gas_price_service/src/v1/da_source_service/block_committer_costs.rs
  crates/services/gas_price_service/src/v1/da_source_service/service.rs
  crates/services/gas_price_service/src/v1/service.rs
  crates/services/gas_price_service/src/v1/uninitialized_task.rs
Labels: no changelog

#2637 Remove netlink proto fix
  Cargo.lock
  crates/services/p2p/Cargo.toml
  version-compatibility/forkless-upgrade/Cargo.toml
  version-compatibility/forkless-upgrade/src/lib.rs
Labels: no changelog

#2640 Bump to 0.40.4 versions
  Cargo.lock
  Cargo.toml
  crates/services/upgradable-executor/src/executor.rs
Labels: no changelog

#2553 fault_proving(global_roots): scaffold global merkle root storage crate
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ci_checks.sh
  crates/fraud_proofs/global_merkle_root/storage/Cargo.toml
  crates/fraud_proofs/global_merkle_root/storage/src/column.rs
  crates/fraud_proofs/global_merkle_root/storage/src/lib.rs
  crates/fraud_proofs/global_merkle_root/storage/src/merkle.rs
  crates/fraud_proofs/global_merkle_root/storage/src/merkle/smt.rs
  crates/fraud_proofs/global_merkle_root/storage/src/structured_storage.rs
  crates/fraud_proofs/global_merkle_root/storage/src/structured_storage/blobs.rs
  crates/fraud_proofs/global_merkle_root/storage/src/structured_storage/coins.rs
  crates/fraud_proofs/global_merkle_root/storage/src/structured_storage/contracts.rs
  crates/fraud_proofs/global_merkle_root/storage/src/structured_storage/messages.rs
  crates/fraud_proofs/global_merkle_root/storage/src/structured_storage/transactions.rs
  crates/fraud_proofs/global_merkle_root/storage/src/structured_storage/upgrades.rs
  crates/fraud_proofs/global_merkle_root/storage/src/update.rs
  crates/storage/src/blueprint/sparse.rs
  crates/storage/src/column.rs
  crates/storage/src/structured_storage/balances.rs
  crates/storage/src/structured_storage/state.rs
Labels: fault-proving

#2649 chore: Add code owners for fraud proofs
  .github/CODEOWNERS
Labels: no changelog

#2651 Refactor `iter_store_keys`
  crates/storage/src/iter/changes_iterator.rs
Labels: no changelog

#2655 chore: Add entire team as code owners for the changelog and `Cargo.lock`
  .github/CODEOWNERS
Labels: no changelog
