Repository FuelLabs/fuel-core, pull requests merged in 2025-05, with the labels that each got.

#2982 fix(tests): flakiness across a few different tests
  crates/fuel-core/src/p2p_test_helpers.rs
  tests/tests/peering.rs
  tests/tests/sync.rs
Labels: no changelog

#2986 chore(backup): allow backups on a live database
  crates/fuel-core/src/combined_database.rs
  crates/fuel-core/src/state/rocks_db.rs
Labels: no changelog

#2995 fix(parallel-executor): clean up for longer lived vecs
  Cargo.lock
  crates/services/parallel-executor/Cargo.toml
  crates/services/parallel-executor/src/column_adapter.rs
  crates/services/parallel-executor/src/lib.rs
  crates/services/parallel-executor/src/scheduler.rs
Labels: no changelog

#3002 chore: Update fuel-vm to 0.61.1
  .changes/breaking/3002.md
  Cargo.lock
  Cargo.toml
  benches/benches/block_target_gas.rs
  benches/benches/vm_set/blockchain.rs
  crates/client/assets/schema.sdl
  crates/client/src/client/schema/primitives.rs
  crates/client/src/client/schema/tx/transparent_receipt.rs
  crates/client/src/client/types/asset.rs
  crates/fuel-core/src/graphql_api/indexation/asset_metadata.rs
  crates/fuel-core/src/graphql_api/storage/assets.rs
  crates/fuel-core/src/schema/scalars.rs
  crates/fuel-core/src/schema/tx/receipt.rs
  crates/services/txpool_v2/src/tests/tests_pool.rs
  crates/storage/src/blueprint/sparse.rs
  tests/test-helpers/src/mint_contract.rs
  tests/tests/assets.rs
  tests/tests/balances.rs
  tests/tests/tx/predicates.rs
Labels: breaking

#3001 chore(parallel-executor): compressed coin validation
  crates/services/parallel-executor/src/coin.rs
  crates/services/parallel-executor/src/lib.rs
  crates/services/parallel-executor/src/scheduler.rs
Labels: no changelog

#3010 chore(parallel-executor): produce mint transaction
  crates/services/executor/src/executor.rs
  crates/services/parallel-executor/src/executor.rs
  crates/services/parallel-executor/src/scheduler.rs
  crates/services/parallel-executor/src/tests/tests_executor.rs
  crates/storage/src/transactional.rs
Labels: no changelog

#2993 fix(graphql): pin the version of assets in the graphql playground
  .changes/fixed/2993.md
  crates/fuel-core/src/graphql_api/api_service.rs
Labels: bug, graphql-api

#2989 fix(port|compression_service): prevent syncing from genesis if compression db is empty
  .changes/fixed/2989.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  bin/fuel-core/src/cli/run.rs
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/adapters/compression_adapters.rs
  crates/fuel-core/src/service/config.rs
  crates/services/compression/src/config.rs
  crates/services/compression/src/ports/block_source.rs
  crates/services/compression/src/service.rs
  crates/services/compression/src/sync_state.rs
  crates/services/src/service.rs
  crates/services/src/state.rs
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/blockchain/header.rs
  tests/tests/da_compression.rs
Labels: bug, tech-debt

#2984 Fix client coins endpoint to return all asset types
  .changes/fixed/2984.md
  crates/client/src/client.rs
  crates/client/src/client/schema/coins.rs
  tests/tests/coin.rs
Labels: cla:signed

#3003 (parallel-executor): Add executor to the scheduler
  Cargo.lock
  crates/services/executor/src/executor.rs
  crates/services/parallel-executor/Cargo.toml
  crates/services/parallel-executor/src/checked_transaction_ext.rs
  crates/services/parallel-executor/src/coin.rs
  crates/services/parallel-executor/src/config.rs
  crates/services/parallel-executor/src/executor.rs
  crates/services/parallel-executor/src/l1_execution_data.rs
  crates/services/parallel-executor/src/lib.rs
  crates/services/parallel-executor/src/once_transaction_source.rs
  crates/services/parallel-executor/src/ports.rs
  crates/services/parallel-executor/src/scheduler.rs
  crates/services/parallel-executor/src/tests/mocks.rs
  crates/services/parallel-executor/src/tests/tests_executor.rs
  crates/services/parallel-executor/src/tx_waiter.rs
  crates/storage/src/transactional.rs
Labels: no changelog

#3018 Apply all suggestions from closed PRs
  .github/workflows/scripts/verify_tag.sh
  README.md
  docs/architecture.md
  docs/developers/debugging.md
  docs/fee_calculations.md
  tests/tests/tx/upgrade.rs
Labels: no changelog

#3026 Update to cargo-sort v2
  .github/workflows/ci.yml
  Cargo.toml
  benches/Cargo.toml
  bin/e2e-test-client/Cargo.toml
  bin/fuel-core/Cargo.toml
  crates/chain-config/Cargo.toml
  crates/client/Cargo.toml
  crates/compression/Cargo.toml
  crates/database/Cargo.toml
  crates/fuel-core/Cargo.toml
  crates/services/Cargo.toml
  crates/services/compression/Cargo.toml
  crates/services/consensus_module/Cargo.toml
  crates/services/consensus_module/poa/Cargo.toml
  crates/services/executor/Cargo.toml
  crates/services/gas_price_service/Cargo.toml
  crates/services/importer/Cargo.toml
  crates/services/p2p/Cargo.toml
  crates/services/parallel-executor/Cargo.toml
  crates/services/producer/Cargo.toml
  crates/services/relayer/Cargo.toml
  crates/services/shared-sequencer/Cargo.toml
  crates/services/sync/Cargo.toml
  crates/services/tx_status_manager/Cargo.toml
  crates/services/txpool_v2/Cargo.toml
  crates/services/upgradable-executor/Cargo.toml
  crates/services/upgradable-executor/wasm-executor/Cargo.toml
  crates/storage/Cargo.toml
  crates/trace/Cargo.toml
  crates/types/Cargo.toml
  tests/Cargo.toml
  xtask/Cargo.toml
Labels: no changelog

#3028 Fix homepage key of Cargo.toml
  Cargo.toml
Labels: no changelog

#3029 chore(parallel-executor): refactor the executor.rs mod
  crates/services/parallel-executor/src/executor.rs
Labels: no changelog

#3032 feat(parallel-executor): dependency graph for validation
  crates/services/parallel-executor/src/validator.rs
  crates/services/parallel-executor/src/validator/dependency_graph.rs
Labels: no changelog
