Repository FuelLabs/fuel-core, pull requests merged in 2025-02, with the labels that each got.

#2617 Add integration skeleton of parallel-executor
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/Cargo.toml
  bin/fuel-core/src/cli/run.rs
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/lib.rs
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/service/sub_services.rs
  crates/services/parallel-executor/Cargo.toml
  crates/services/parallel-executor/src/config.rs
  crates/services/parallel-executor/src/executor.rs
  crates/services/parallel-executor/src/lib.rs
  crates/services/upgradable-executor/src/lib.rs
Labels: xxx

#2621 Handle new state transition bytecode and new consensus parameter version
  CHANGELOG.md
  Cargo.lock
  crates/fraud_proofs/global_merkle_root/storage/Cargo.toml
  crates/fraud_proofs/global_merkle_root/storage/src/update.rs
Labels: fault-proving

#2652 Fault proving: Populate ContractsRawCode when processing Create Transaction in global merkle root crate
  CHANGELOG.md
  crates/fraud_proofs/global_merkle_root/storage/src/update.rs
Labels: fault-proving

#2665 fix(notify_cancel): removed usage of async trait and made the trait dyn incompatible
  crates/fuel-core/src/lib.rs
  crates/fuel-core/src/service/genesis/exporter.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/fuel-core/src/service/genesis/importer/import_task.rs
  crates/fuel-core/src/service/genesis/task_manager.rs
Labels: no changelog

#2677 fix: Remove dangerous array lookup
  crates/fraud_proofs/global_merkle_root/storage/src/update.rs
Labels: no changelog

#2670 Refactor all the gas price cli args, fix downstream problems
  bin/e2e-test-client/tests/integration_tests.rs
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/run/gas_price.rs
  crates/fuel-core/src/p2p_test_helpers.rs
  crates/fuel-core/src/service/adapters/gas_price_adapters.rs
  crates/fuel-core/src/service/config.rs
  crates/fuel-core/src/service/sub_services.rs
  tests/test-helpers/src/builder.rs
  tests/tests/chain.rs
  tests/tests/gas_price.rs
Labels: no changelog

#2647 Add versions on readme with action to update
  .github/workflows/update_readme_versions.yml
  README.md
Labels: no changelog

#2678 fix(headers): move tx_id_commitment to application_headers
  CHANGELOG.md
  Cargo.lock
  bin/fuel-core/src/cli/snapshot.rs
  crates/chain-config/src/config/state.rs
  crates/compression/src/compressed_block_payload/v1.rs
  crates/fraud_proofs/global_merkle_root/storage/src/update.rs
  crates/fuel-core/src/executor.rs
  crates/fuel-core/src/query/message/test.rs
  crates/fuel-core/src/schema/block.rs
  crates/fuel-core/src/schema/dap.rs
  crates/fuel-core/src/service/adapters/consensus_module.rs
  crates/fuel-core/src/service/adapters/consensus_parameters_provider.rs
  crates/fuel-core/src/service/adapters/graphql_api/on_chain.rs
  crates/fuel-core/src/service/genesis.rs
  crates/fuel-core/src/service/genesis/importer.rs
  crates/services/consensus_module/Cargo.toml
  crates/services/consensus_module/poa/src/verifier.rs
  crates/services/consensus_module/poa/src/verifier/tests.rs
  crates/services/consensus_module/src/block_verifier.rs
  crates/services/consensus_module/src/block_verifier/tests.rs
  crates/services/executor/src/executor.rs
  crates/services/gas_price_service/src/common/l2_block_source.rs
  crates/services/gas_price_service/src/v0/uninitialized_task.rs
  crates/services/gas_price_service/src/v1/uninitialized_task.rs
  crates/services/p2p/Cargo.toml
  crates/services/p2p/src/p2p_service.rs
  crates/services/producer/src/block_producer.rs
  crates/services/producer/src/block_producer/tests.rs
  crates/services/sync/src/import.rs
  crates/services/upgradable-executor/src/executor.rs
  crates/types/Cargo.toml
  crates/types/src/blockchain/block.rs
  crates/types/src/blockchain/header.rs
  crates/types/src/blockchain/header/v1.rs
  crates/types/src/blockchain/header/v2.rs
Labels: breaking

#2700 Remove unexpected logs
  crates/services/sync/src/import/cache.rs
Labels: no changelog

#2703 fix: Typo in test comment
  crates/fraud_proofs/global_merkle_root/storage/src/update.rs
Labels: no changelog

#2704 Remove analysis code
  crates/fuel-gas-price-algorithm/gas-price-analysis/.gitignore
  crates/fuel-gas-price-algorithm/gas-price-analysis/Cargo.toml
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/charts.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/main.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/optimisation.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation.rs
  crates/fuel-gas-price-algorithm/gas-price-analysis/src/simulation/da_cost_per_byte.rs
Labels: no changelog

#2712 Port the update of versions 0.41.7
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  bin/fuel-core/chainspec/local-testnet/chain_config.json
  crates/chain-config/src/config/snapshots/fuel_core_chain_config__config__chain__tests__snapshot_local_testnet_config.snap
  crates/services/upgradable-executor/src/executor.rs
  crates/types/src/blockchain/header.rs
Labels: no changelog

#2491 Execution tracing: GraphQL query to get storage inputs for past blocks
  CHANGELOG.md
  Cargo.toml
  bin/fuel-core/src/cli/run.rs
  bin/fuel-core/src/cli/run/graphql.rs
  crates/client/assets/schema.sdl
  crates/client/src/client.rs
  crates/client/src/client/schema.rs
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__storage_read_replay__tests__execution_trace_block_tx_gql_output.snap
  crates/client/src/client/schema/snapshots/fuel_core_client__client__schema__storage_read_replay__tests__storage_read_replay_gql_output.snap
  crates/client/src/client/schema/storage_read_replay.rs
  crates/client/src/client/schema/tx.rs
  crates/fuel-core/src/graphql_api.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/schema/tx.rs
  crates/fuel-core/src/schema/tx/types.rs
  crates/fuel-core/src/service/adapters/graphql_api.rs
  crates/fuel-core/src/service/adapters/producer.rs
  crates/fuel-core/src/service/config.rs
  crates/services/executor/src/executor.rs
  crates/services/producer/src/block_producer.rs
  crates/services/producer/src/mocks.rs
  crates/services/producer/src/ports.rs
  crates/services/upgradable-executor/Cargo.toml
  crates/services/upgradable-executor/src/executor.rs
  crates/services/upgradable-executor/src/lib.rs
  crates/services/upgradable-executor/src/storage_access_recorder.rs
  crates/types/src/services/executor.rs
  tests/test-helpers/src/counter_contract.rs
  tests/tests/assets.rs
  tests/tests/gas_price.rs
  tests/tests/lib.rs
  tests/tests/state_rewind.rs
  tests/tests/storage_read_replay.rs
Labels: enhancement, fuel-block-executor, wasm

#2729 docs: Fix Readme links
  README.md
Labels: no changelog

#2719 fault_proving(merklized_registry): add merklized registry tables
  .changes/added/2719.md
  crates/fuel-core/Cargo.toml
  crates/fuel-core/src/graphql_api/storage.rs
  crates/fuel-core/src/graphql_api/storage/da_compression.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/reverse_key.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/address.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/asset_id.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/contract_id.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/evictor_cache.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/predicate_code.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/registry_index.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/script_code.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/timestamps.rs
  crates/storage/src/blueprint/merklized.rs
Labels: fault-proving

#2744 chore: Add whole team as codeowners for new changelog folder
  .github/CODEOWNERS
Labels: no changelog

#2745 chore: Minor comments clean-up
  crates/fuel-core/src/graphql_api/indexation/coins_to_spend.rs
  crates/services/gas_price_service/src/v1/service.rs
Labels: no changelog

#2736 Use the state of the database before the benchmark
  benches/src/lib.rs
Labels: no changelog

#2747 Refactor poa service
  crates/services/consensus_module/poa/src/service.rs
Labels: no changelog

#2750 Dedicated threads for the block importer
  CHANGELOG.md
  Cargo.lock
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/block_importer.rs
  crates/fuel-core/src/service/genesis.rs
  crates/services/importer/Cargo.toml
  crates/services/importer/src/error.rs
  crates/services/importer/src/importer.rs
  crates/services/importer/src/importer/test.rs
  crates/services/importer/src/lib.rs
  crates/services/importer/src/local_runner.rs
  crates/services/importer/src/ports.rs
  tests/tests/recovery.rs
  tests/tests/trigger_integration/instant.rs
Labels: no changelog

#2619 Add possibility to submit a list of changes to rocksdb
  .changes/added/2619.md
  crates/database/src/lib.rs
  crates/fuel-core/src/database.rs
  crates/fuel-core/src/executor.rs
  crates/fuel-core/src/service.rs
  crates/fuel-core/src/service/genesis/importer/import_task.rs
  crates/fuel-core/src/state.rs
  crates/fuel-core/src/state/historical_rocksdb.rs
  crates/fuel-core/src/state/historical_rocksdb/view_at_height.rs
  crates/fuel-core/src/state/in_memory/memory_store.rs
  crates/fuel-core/src/state/rocks_db.rs
  crates/storage/src/iter/changes_iterator.rs
  crates/storage/src/transactional.rs
Labels: xxx

#2618 Parallelise block/transaction changes creation in Importer
  .changes/changed/2618.md
  Cargo.lock
  crates/fuel-core/src/service/adapters.rs
  crates/fuel-core/src/service/adapters/block_importer.rs
  crates/fuel-core/src/service/genesis.rs
  crates/services/importer/Cargo.toml
  crates/services/importer/src/error.rs
  crates/services/importer/src/importer.rs
  crates/services/importer/src/importer/test.rs
  crates/services/importer/src/lib.rs
  crates/services/importer/src/local_runner.rs
  crates/services/importer/src/ports.rs
  tests/tests/recovery.rs
  tests/tests/trigger_integration/instant.rs
Labels: xxx

#2731 fault_proving(compression): temporal registry implementations
  .changes/added/2731.md
  crates/fuel-core/src/graphql_api/da_compression.rs
  crates/fuel-core/src/graphql_api/ports.rs
  crates/fuel-core/src/graphql_api/storage/da_compression/v2/evictor_cache.rs
Labels: fault-proving

#2764 fix(version-compatibility): remove old/unused version compat tests
  version-compatibility/0.14.1-0.15.0/fuel-core-0.14.1-client-0.15.0/Cargo.toml
  version-compatibility/0.14.1-0.15.0/fuel-core-0.14.1-client-0.15.0/test.rs
  version-compatibility/0.14.1-0.15.0/fuel-core-0.15.0-client-0.14.1/Cargo.toml
  version-compatibility/0.14.1-0.15.0/fuel-core-0.15.0-client-0.14.1/test.rs
  version-compatibility/Cargo.toml
Labels: no changelog

#2751 Move p2p tests to own files
  crates/services/p2p/src/p2p_service.rs
  crates/services/p2p/src/p2p_service/tests.rs
  crates/services/p2p/src/service.rs
  crates/services/p2p/src/service/broadcast_tests.rs
  crates/services/p2p/src/service/task_tests.rs
Labels: no changelog
